$.extend($,{strlen:function(a){return"string"!=typeof a?0:a.replace(/[^\x00-\xff]/gi,"xx").length}});var G={};G.domain=/51buy\.com/.test(location.host)?"51buy.com":"yixun.com";G.DOMAIN={WWW_ICSON_COM:"www."+G.domain,ACT_ICSON_COM:"act."+G.domain,EVENT_ICSON_COM:"event."+G.domain,ITEM_ICSON_COM:"item."+G.domain,BUY_ICSON_COM:"buy."+G.domain,BASE_ICSON_COM:"base."+G.domain,S_ICSON_COM:"s."+G.domain,LIST_ICSON_COM:"list."+G.domain,ST_ICSON_COM:"st."+G.domain,ACT_ICSON_COM:"act."+G.domain};
G.prefix={st:"http://st."+G.domain+"/",ssl:!1,st_ssl:"https://st."+G.domain+"/"};G.createFnQueue=function(a){var b=[];return{add:function(a){$.isFunction(a)&&b.push(a)},exec:function(c){if(!1!==a)for(;0<b.length;)b.shift()(c);else for(var d=0,e=b.length;d<e;d++)if(!1===b[d](c))return!1},clear:function(){b.length=0}}};G.app={};G.logic={};G.ui={};G.util={};if($.browser.msie&&7>parseInt($.browser.version,10))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(e$$12){}
G.util.cookie={get:function(a){a=document.cookie.match(RegExp("(^|;|\\s+)"+a+"=([^;]*)(;|$)"));return!a?"":unescape(a[2])},add:function(a,b,c,d,e){a=a+"="+escape(b)+"; path="+(c||"/")+(e?"; domain="+e:"");0<d&&(b=new Date,b.setTime(b.getTime()+1E3*d),a+=";expires="+b.toGMTString());document.cookie=a},del:function(a,b){document.cookie=a+"=;path=/;"+(b?"domain="+b+";":"")+"expires="+(new Date(0)).toGMTString()}};
G.util.token={addToken:function(a,b){var c=this.getToken();if(""==a||0!=(0>a.indexOf("://")?location.href:a).indexOf("http"))return a;if(-1!=a.indexOf("#")){var d=a.match(/\?.+\#/);if(d){var e=d[0].split("#"),c=[e[0],"&g_tk=",c,"&g_ty=",b,"#",e[1]].join("");return a.replace(d[0],c)}e=a.split("#");return[e[0],"?g_tk=",c,"&g_ty=",b,"#",e[1]].join("")}return""==c?a+(-1!=a.indexOf("?")?"&":"?")+"g_ty="+b:a+(-1!=a.indexOf("?")?"&":"?")+"g_tk="+c+"&g_ty="+b},getToken:function(){var a=G.util.cookie.get("skey");
return null==a?"":this.time33(a)},time33:function(a){for(var b=0,c=a.length,d=5381;b<c;++b)d+=(d<<5)+a.charAt(b).charCodeAt();return d&2147483647}};var Mustache;
(function(a){"undefined"!==typeof module&&module.exports?module.exports=a:"function"===typeof define?define(a):Mustache=a})(function(){function a(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function b(a){this.tail=this.string=a;this.pos=0}function c(a,b){this.view=a;this.parent=b;this.clearCache()}function d(){this.clearCache()}function e(a){for(var b=a[3],c=b,d;(d=a[4])&&d.length;)a=d[d.length-1],c=a[3];return[b,c]}function f(a){function b(a,d,e){if(!c[a]){var h=f(d);c[a]=function(a,
b){return h(a,b,e)}}return c[a]}var c={};return function(c,d,f){for(var h="",g,k,l=0,m=a.length;l<m;++l)switch(g=a[l],g[0]){case "#":k=f.slice.apply(f,e(g));h+=c._section(g[1],d,k,b(l,g[4],f));break;case "^":h+=c._inverted(g[1],d,b(l,g[4],f));break;case ">":h+=c._partial(g[1],d);break;case "&":h+=c._name(g[1],d);break;case "name":h+=c._escaped(g[1],d);break;case "text":h+=g[1]}return h}}function h(b){if(2!==b.length)throw Error("Invalid tags: "+b.join(" "));return[RegExp(a(b[0])+"\\s*"),RegExp("\\s*"+
a(b[1]))]}var g={name:"mustache.js",version:"0.7.0",tags:["{{","}}"]};g.Scanner=b;g.Context=c;g.Writer=d;var k=/\s*/,l=/\s+/,m=/\S/,n=/\s*=/,q=/\s*\}/,t=/#|\^|\/|>|\{|&|=|!/,p=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},s={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"};g.escape=function(a){return String(a).replace(/[&<>"'\/]/g,function(a){return s[a]})};b.prototype.eos=function(){return""===this.tail};b.prototype.scan=function(a){return(a=
this.tail.match(a))&&0===a.index?(this.tail=this.tail.substring(a[0].length),this.pos+=a[0].length,a[0]):""};b.prototype.scanUntil=function(a){var b=this.tail.search(a);switch(b){case -1:a=this.tail;this.pos+=this.tail.length;this.tail="";break;case 0:a="";break;default:a=this.tail.substring(0,b),this.tail=this.tail.substring(b),this.pos+=b}return a};c.make=function(a){return a instanceof c?a:new c(a)};c.prototype.clearCache=function(){this._cache={}};c.prototype.push=function(a){return new c(a,this)};
c.prototype.lookup=function(a){var b=this._cache[a];if(!b){if("."===a)b=this.view;else for(var c=this;c;){if(0<a.indexOf("."))for(var d=a.split("."),f=0,b=c.view;b&&f<d.length;)b=b[d[f++]];else b=c.view[a];if(null!=b)break;c=c.parent}this._cache[a]=b}"function"===typeof b&&(b=b.call(this.view));return b};d.prototype.clearCache=function(){this._cache={};this._partialCache={}};d.prototype.compile=function(a,b){var c=this._cache[a];c||(c=g.parse(a,b),c=this._cache[a]=this.compileTokens(c,a));return c};
d.prototype.compilePartial=function(a,b,c){b=this.compile(b,c);return this._partialCache[a]=b};d.prototype.compileTokens=function(a,b){var d=f(a),e=this;return function(a,f){if(f)if("function"===typeof f)e._loadPartial=f;else for(var h in f)e.compilePartial(h,f[h]);return d(e,c.make(a),b)}};d.prototype.render=function(a,b,c){return this.compile(a)(b,c)};d.prototype._section=function(a,b,c,d){a=b.lookup(a);switch(typeof a){case "object":if(p(a)){c="";for(var f=0,e=a.length;f<e;++f)c+=d(this,b.push(a[f]));
return c}return a?d(this,b.push(a)):"";case "function":var h=this;d=a.call(b.view,c,function(a){return h.render(a,b)});return null!=d?d:"";default:if(a)return d(this,b)}return""};d.prototype._inverted=function(a,b,c){a=b.lookup(a);return!a||p(a)&&0===a.length?c(this,b):""};d.prototype._partial=function(a,b){!(a in this._partialCache)&&this._loadPartial&&this.compilePartial(a,this._loadPartial(a));var c=this._partialCache[a];return c?c(b):""};d.prototype._name=function(a,b){var c=b.lookup(a);"function"===
typeof c&&(c=c.call(b.view));return null==c?"":String(c)};d.prototype._escaped=function(a,b){return g.escape(this._name(a,b))};g.parse=function(c,d){d=d||g.tags;for(var f=h(d),e=new b(c),p=[],s=[],r=!1,y=!1,x,u,v;!e.eos();){x=e.pos;if(v=e.scanUntil(f[0]))for(var A=0,B=v.length;A<B;++A)if(u=v.charAt(A),RegExp.prototype.test.call(m,u)?y=!0:s.push(p.length),p.push(["text",u,x,x+1]),x+=1,"\n"===u){if(r&&!y)for(;s.length;)p.splice(s.pop(),1);else s=[];y=r=!1}x=e.pos;if(!e.scan(f[0]))break;r=!0;u=e.scan(t)||
"name";e.scan(k);"="===u?(v=e.scanUntil(n),e.scan(n),e.scanUntil(f[1])):"{"===u?(v=RegExp("\\s*"+a("}"+d[1])),v=e.scanUntil(v),e.scan(q),e.scanUntil(f[1]),u="&"):v=e.scanUntil(f[1]);if(!e.scan(f[1]))throw Error("Unclosed tag at "+e.pos);p.push([u,v,x,e.pos]);if("name"===u||"{"===u||"&"===u)y=!0;"="===u&&(d=v.split(l),f=h(d))}for(var f=p,w,p=[],s=0;s<f.length;++s)e=f[s],w&&"text"===w[0]&&"text"===e[0]?(w[1]+=e[1],w[3]=e[3]):(w=e,p.push(e));w=p;r=f=[];e=[];for(s=0;s<w.length;++s)switch(p=w[s],p[0]){case "#":case "^":p[4]=
[];e.push(p);r.push(p);r=p[4];break;case "/":if(0===e.length)throw Error("Unopened section: "+p[1]);r=e.pop();if(r[1]!==p[1])throw Error("Unclosed section: "+r[1]);r=0<e.length?e[e.length-1][4]:f;break;default:r.push(p)}if(r=e.pop())throw Error("Unclosed section: "+r[1]);return f};var r=new d;g.clearCache=function(){return r.clearCache()};g.compile=function(a,b){return r.compile(a,b)};g.compilePartial=function(a,b,c){return r.compilePartial(a,b,c)};g.compileTokens=function(a,b){return r.compileTokens(a,
b)};g.render=function(a,b,c){return r.render(a,b,c)};g.to_html=function(a,b,c,d){a=g.render(a,b,c);if("function"===typeof d)d(a);else return a};return g}());
G.util.post=function(a,b,c){G.util.post.pIndex=(G.util.post.pIndex||0)+1;var d=$('<iframe name="pIframe_'+G.util.post.pIndex+'" src="about:blank" style="display:none" width="0" height="0" scrolling="no" allowtransparency="true" frameborder="0"></iframe>').appendTo($(document.body)),e=[];$.each(b,function(a,b){e.push('<input type="hidden" name="'+a+'" value="" />')});/(\?|&(amp;)?)fmt=[^0 &]+/.test(a)||(a+=(0<a.indexOf("?")?"&":"?")+"fmt=1");var f=$('<form action="'+a+'" method="post" target="pIframe_'+
G.util.post.pIndex+'">'+e.join("")+"</form>").appendTo($(document.body));$.each(b,function(a,b){f.children("[name="+a+"]").val(b)});d[0].callback=function(a){"function"==typeof c&&c(a);$(this).src="about:blank";$(this).remove();f.remove();d=f=null};$.browser.msie&&6==$.browser.version?(d[0].pIndex=G.util.post.pIndex,d[0].ie6callback=function(){f.target="pIframe_"+this.pIndex;f.submit()},d[0].src=location.protocol+"//st."+G.domain+"/static_v1/htm/ie6post.htm"):f.submit()};
G.util.getACSRFToken=function(){return G.util.cookie.get("g_tk")?G.util._DJB(G.util.cookie.get("g_tk")):!1};G.util._DJB=function(a){for(var b=5381,c=0,d=a.length;c<d;++c)b+=(b<<5)+a.charAt(c).charCodeAt();return b&2147483647};G.util.token_post=function(a){var b=jQuery.extend({type:"POST",cache:!1,dataType:"json",timeout:8E3},a);G.util.getACSRFToken()&&(b.url=a.url+"&token="+G.util.getACSRFToken());jQuery.ajax(b)};
G.util.parse={url:function(){var a=function(a){a=(a+"").replace(/(&amp;|\?)/g,"&").split("&");for(var b={},e=a.length,f=0;f<e;f++){var h=a[f].indexOf("=");-1!=h&&(b[a[f].substr(0,h).replace(/[^a-zA-Z0-9_]/g,"")]=unescape(a[f].substr(h+1)))}return b},b=location.href.toString().indexOf("#"),b=0>b?"":location.href.toString().substring(b,location.href.toString().length);return{search:a(location.search.substr(1)),hash:a(b)}},encodeHtml:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;").replace(/'/g,"&#039;").replace(/"/g,"&quot;")},decodeHtml:function(a){return a.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#0?39;/g,"'").replace(/&quot;/g,'"').replace(/&amp;/g,"&")},timeFormat:function(a,b){var c=G.util.parse.getTimeInfo(a),d={y:c.year,m:c.month,d:c.date,h:c.hour,i:c.minute,s:c.sec,w:c.week};$.each(d,function(a,b){"y"!=a&&10>b&&(d[a]="0"+b)});return b.replace(/(?!\\)(y|m|d|h|i|s|w)/gi,function(a,b){return d[b.toLowerCase()]})},getTimeInfo:function(a){a=new Date(1E3*
a);return{year:a.getFullYear(),month:a.getMonth()+1,date:a.getDate(),hour:a.getHours(),minute:a.getMinutes(),sec:a.getSeconds(),week:"星期天 星期一 星期二 星期三 星期四 星期五 星期六".split(" ")[a.getDay()]}},jsonToStr:function(a){if("number"==typeof a)return isFinite(a)?a.toString():'""';if("string"==typeof a)return'"'+a.replace(/(\\|\")/g,"\\$1").replace(/\n|\r|\t/g,function(a){return"\n"==a?"\\n":"\r"==a?"\\r":"\t"==a?"\\t":""})+'"';if("boolean"==typeof a)return a?"true":"false";if($.isArray(a)){for(var b="",c=0;c<
a.length;c++)b=""==b?G.util.parse.jsonToStr(a[c]):b+(","+G.util.parse.jsonToStr(a[c]));return"["+b+"]"}if($.isPlainObject(a)){b="";for(c in a)b=""==b?'"'+c+'":'+G.util.parse.jsonToStr(a[c]):b+(',"'+c+'":'+G.util.parse.jsonToStr(a[c]));return"{"+b+"}"}return'""'}};
G.util.localShare=function(){var a=G.createFnQueue(),b=0,c=!1;return function(d){a.add(d);2==b&&c?a.exec(c):1!=b&&(b=1,$.ajax({url:"http://st.icson.com/static_v1/js/app/localShare.js?v=1.1",dataType:"script",crossDomain:!0,cache:!0,scriptCharset:"gb2312",success:function(){G.app.localShare(function(){b=2;c=this;a.exec(c)})}}))}}();
G.util.ping={VISIT_INFO_KEY:"vinfo",_visMap:["lastVisit"],_performance:!1,getVisitInfo:function(){var a=G.util.ping,b=G.util.cookie.get(a.VISIT_INFO_KEY),c={},b=b.split(",");$.each(a._visMap,function(a,e){c[e]=b[a]||""});return c},setVisitInfo:function(a,b){var c=G.util.ping,d=c.getVisitInfo(),e={},f=[];2>arguments.length?e=a:e[a]=b;d=$.extend(d,a);$.each(c._visMap,function(a,b){f[a]=d[b]||""});G.util.cookie.add(c.VISIT_INFO_KEY,f.join(","),"/",31536E3,"."+G.domain)},getPerformanceTiming:function(){var a=
G.util.ping;if(!1===a._performance){var b=window.performance;if(!b||!b.timing)return[];for(var c="navigationStart unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),d=[],e=c.length-1;1<=e;e--)d[e]=b.timing[c[e]]-b.timing[c[0]];a._performance=d}return a._performance},
timeStat:function(){return function(a,b,c,d){a=function(a,b,c,d){return function(){if(!("array"==$.type(a)&&0==a.length||$.isEmptyObject(a))){var k=["flag1=1470","flag2="+b,"flag3="+c],l=new Image;$.each(a,function(a,b){0!=a&&k.push(a+"="+(0>=b?0:b))});d=d||{};for(var m in d)k.push(m+"="+d[m]);l.src="http://isdspeed.qq.com/cgi-bin/r.cgi?"+k.join("&")}}}(a,b,c,d);setTimeout(a,2E3)}}(),reportPerformance:function(a,b,c){var d=window.onload;window.onload=function(){$.isFunction(d)&&d.apply(window);d=
null;setTimeout(function(){G.util.ping.timeStat(G.util.ping.getPerformanceTiming(),a,b,c)},2E3)}},reportItemPicLoad:function(a,b){var c=(new Date).getTime()-a,d="http://isdspeed.qq.com/cgi-bin/r.cgi?flag1=1470&flag2=50&flag3="+(b?9:10)+"&1="+c;setTimeout(function(){(new Image).src=d},2E3)},init:function(a,b){}};
(function(a,b,c){function d(a){var c,h,g,k;if(!this||!(this.hasOwnProperty&&this instanceof d))return new d(a);a=jQuery.extend({},{position:"rightBottom",distance:20,width:"120",html:"",target:null,buttons:null,group:null,className:"global_tip",time:null},a||{});var l=this,m=b(a.target);(g=m.data("tipInstnace"))&&g.close();d.instance=d.instance||[];if(a.group){g=0;for(c=d.instance.length;g<c;g++)d.instance[g].opt.group===a.group&&d.instance[g].close()}g=a.buttons&&!b.isArray(a.buttons)||b.isArray(a.buttons)&&
0<a.buttons.length;this.element=b('<div class="'+a.className+'"><div class="content">'+a.html+"</div>"+(g?'<div class="buttons"></div>':"")+'<span class="arrow">◆<span class="inner">◆</span></span></div>').css("width",a.width);this.opt=a;this.opt.id=(new Date).getTime();g&&(c=b.map(b.isArray(a.buttons)?a.buttons:[a.buttons],function(a,b){return'<a href="#" onclick="return false" class="'+(0==b?"btn_strong":"btn_common")+'">'+a+"</a>"}).join(""),k=this.element.find(".buttons"),k.append(c),k.find("a").each(function(a){b(this).click(function(){!1!==
l.element.triggerHandler("click_"+(a+1))&&l.close()})}).first().focus());this.element.appendTo(document.body);!g&&a.time&&(this.timer=setTimeout(function(){l.close()},parseInt(a.time,10)));g={};k={};g=parseInt(a.distance,10);c=b.browser.mozilla?12:b.browser.webkit?12:13;switch(a.position){case "leftTop":g={bottom:-1*c,right:g};k={top:-1};break;case "rightTop":g={left:g,bottom:-1*c};k={top:-1};break;case "leftBottom":g={top:-10,right:g};k={top:1};break;default:g={top:-10,left:g},k={top:1}}c=b(".arrow",
this.element);c.css(g);b(".inner",this.element).css(k);k=c.offset();h=m.offset();switch(a.position){case "leftTop":case "rightTop":g=parseInt(k.left,10)+parseInt(c.width(),10)/2;k=parseInt(k.top,10)+parseInt(c.height(),10);c=parseInt(h.left,10)+parseInt(m.width(),10)/2;h=parseInt(h.top,10);break;default:g=parseInt(k.left,10)+parseInt(c.width(),10)/2,k=parseInt(k.top,10),c=parseInt(h.left,10)+parseInt(m.width(),10)/2,h=parseInt(h.top,10)+parseInt(m.height(),10)}var n=this.element.position();this.element.css({left:parseInt(n.left)-
g+c,top:parseInt(n.top)-k+h});l=this;l._close=function(){l&&l.close()};b(window).bind("resize",l._close);d.instance.push(this);m.data("tipInstnace",this);for(var q in a)/^click_\d$/.test(q.toString())&&this.bind(q,a[q])}b.extend(d.prototype,{bind:function(){this.element.bind.apply(this.element,b.makeArray(arguments))},close:function(){clearTimeout(this.timer);b(window).unbind("resize",self._close);this.element.data("tipInstnace",null);for(var a=0,c=d.instance.length;a<c;a++)if(d.instance[a].opt.id==
this.opt.id){d.instance.splice(a,1);break}this.element.remove()},getButtons:function(){return this.element.find(".buttons>a")},getElement:function(){return this.element},isShow:function(){return"none"!==this.element[0].style.display},show:function(){this.element[0].style.display="block"},hide:function(){this.element[0].style.display="none"}});a.ui.arrowTip=d})(G,jQuery);
(function(a,b,c){function d(a){this.opt=b.extend({},{tpl:"",itemActiveClass:"",data:null,index:-1,url:""},a||{});this.init()}function e(a){if(!(this.hasOwnProperty&&this instanceof e))return new e(a);this.opt=b.extend({},{target:null,listOnClass:"",delayTime:200,elementClass:"autocomplete",cache:!0,itemTPL:"<li>{label}</li>",itemActiveClass:"on",params:"",keyName:"kw",cache:!0},a||{});a=b(this.opt.target);if(0===a.length)return null;this.target=a.eq(0);this.items=[];this.init()}d.prototype={constructor:d,
trigger:function(){this.element&&this.element.triggerHandler.apply(this.element,Array.prototype.slice.call(arguments,0,arguments.length))},bind:function(){this.element&&this.element.bind.apply(this.element,Array.prototype.slice.call(arguments,0,arguments.length))},init:function(){var a=this,d=this.opt.tpl.toString().replace(/{([^}]+)}/g,function(b,d){return c===a.opt.data[d]?"":a.opt.data[d]});this.element=b(d);this.element.hover(function(){a.active()},function(){a.unActive()}).click(function(){a.trigger("item_click",
a.opt.data);return!1})},active:function(){this.element&&this.element.addClass(this.opt.itemActiveClass);this.mouseIn=!0;this.trigger("active",this.opt.index)},unActive:function(){this.mouseIn=!1;this.element&&this.element.removeClass(this.opt.itemActiveClass);this.trigger("unactive")},remove:function(){this.element.remove()},isActive:function(){return!!this.mouseIn},getData:function(){return this.opt.data}};e.prototype={constructor:e,keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,
COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91},resize:function(){var a=this.target,b=a.offset();this.element.css({left:b.left||0,top:(parseFloat(b.top,10)||0)+(parseFloat(a.outerHeight(),10)||0)-(parseFloat(a.css("border-bottom-width"),10)||0)})},
init:function(){var c=this;this.element=b('<ul class="'+this.opt.elementClass+'"></ul>');b(a).bind("resize",function(){c.resize()});this.resize();this.items=[];this.target.click(function(){0<c.items.length&&c.show()});this.target.bind("keydown.autocomplete",function(a){c.bindKeyDown(a)});this.target.bind("keyup.autocomplete",function(a){a=a.keyCode;var b=c.keyCode;a===b.UP||(a===b.DOWN||a===b.ENTER||a===b.NUMPAD_ENTER||a===b.LEFT||a===b.RIGHT)||c.queryDelaySend()});this.target.bind("enter.autocomplete",
function(){c.hide()});this.target.bind("click.autocomplete",function(){c.hide()});this.target.bind("blur",function(){setTimeout(function(){c.hide()},200)})},destory:function(){},ajax:function(a){var d=this;d.hide();this.term=a;this.cache=this.cache||{};if(this.opt.cache&&c!==d.cache[a])d.requestSuccess(d.cache[a]);else{var e={};d.opt.keyName&&(e[d.opt.keyName]=a);d.xhr&&d.xhr.abort();d.xhr=b.ajax({url:d.opt.url,data:b.extend(e,d.opt.params||{}),async:!0,dataType:"jsonp",cache:!1,crossDomain:!0,scriptCharset:"gb2312",
success:function(b){d.opt.cache&&(d.cache[a]=b);d.requestSuccess(b)}})}},requestSuccess:function(a){a={response:a};this.trigger("success",a);this.hide();if(b.isArray(a.response)){for(var c=0,e=a.response.length;c<e;c++){var k=new d({data:a.response[c],tpl:this.opt.itemTPL,itemActiveClass:this.opt.itemActiveClass,itemTPL:this.opt.itemTPL,index:c});this.bindItem(k);this.element.append(k.element);this.items.push(k)}0<a.response.length&&this.show()}},bindItem:function(a){var b=this;a.bind("item_click",
function(c,d){b.target[0].value=d.value;b.hide();b.trigger("complete",{from:"click",index:a.opt.index})});a.bind("active",function(a,c){for(var d=0,f=b.items.length;d<f;d++)d!==c&&b.items[d].unActive()})},bindKeyDown:function(a){var b=this.keyCode;switch(a.keyCode){case b.UP:this.isActive()&&(this.prev(),a.preventDefault());break;case b.DOWN:this.isActive()&&(this.next(),a.preventDefault());break;case b.ENTER:case b.NUMPAD_ENTER:this.trigger("enter");case b.ESCAPE:this.hide(a)}},queryDelaySend:function(){var a=
this;clearTimeout(a.delayTimer);a.delayTimer=setTimeout(function(){var c=a.target[0].value;a.term!==c&&(""!==b.trim(c)?a.ajax(c):(a.term="",a.xhr&&a.xhr.abort(),a.hide()))},a.opt.delayTime)},show:function(){this.resize();this.activeStatus=!0;this.element&&this.element.addClass(this.opt.listOnClass);this.element.appendTo("body");this.trigger("show")},hide:function(){this.activeStatus=!1;this.element&&this.element.removeClass(this.opt.listOnClass);this.element.detach();for(var a=0,b=this.items.length;a<
b;a++)this.items[a].remove();this.items=[];this.trigger("hide")},getActiveIndex:function(){for(var a=-1,b=0,c=this.items.length;b<c;b++)if(!0===this.items[b].isActive()){a=b;break}return a},prev:function(){var a=this.getActiveIndex();-1!==a&&(this.items[a].unActive(),this.target.val(this.term));a=(-1===a?this.items.length:a)-1;-1<a&&(a=this.items[a],a.active(),this.target.val(a.getData().value))},next:function(){var a=this.getActiveIndex();-1!==a&&(this.items[a].unActive(),this.target.val(this.term));
a+1<this.items.length&&(a=this.items[a+1],a.active(),this.target.val(a.getData().value))},isActive:function(){return!!this.activeStatus},trigger:function(){this.element&&this.element.triggerHandler.apply(this.element,Array.prototype.slice.call(arguments,0,arguments.length))},bind:function(){this.element&&this.element.bind.apply(this.element,Array.prototype.slice.call(arguments,0,arguments.length))}};G.ui.autoComplete=e})(window,jQuery);
(function(a,b,c,d){var e=function(a,c){this.instance="jswf_"+(new Date).getTime();var g=this.options=b.extend({},e.options,c),k=this.id=g.id||this.instance,l=b(g.container||"<div></div>");e.CallBacks[this.instance]={};var m=g.params,n=g.vars,q=g.callBacks,g=b.extend({},{height:g.height,width:g.width},g.properties),t=this,p;for(p in q)e.CallBacks[this.instance][p]=function(a){return function(){return a.apply(t.object,arguments)}}(q[p]),n[p]="G.ui.swf.CallBacks."+this.instance+"."+p;m.flashVars=b.param(n);
b.browser.msie?(g.classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",g.codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0",m.movie=a):(g.type="application/x-shockwave-flash",g.data=a);var s=['<object id="',k,'"'],r;for(r in g)s.push(" ",r,'="',g[r],'"');s.push(">");for(var z in m)m[z]!==d&&s.push('<param name="',z,'" value="',m[z],'" />');s.push("</object>");b.each(l,function(a,b){b.innerHTML=s.join("")});this.getObject()};b.extend(e,{options:{id:null,
height:1,width:1,container:null,properties:{align:"middle"},params:{quality:"high",allowScriptAccess:"always",wMode:"transparent",swLiveConnect:!0,menu:!1},callBacks:{},vars:{}},CallBacks:{},remote:function(a,b){var c=a.CallFunction('<invoke name="'+b+'" returntype="javascript">'+__flash__argumentsToXML(arguments,2)+"</invoke>");return eval(c)}});b.extend(e.prototype,{toElement:function(){return this.object},getObject:function(){var a=this;(this.object=document[this.id]||c[this.id])||setTimeout(function(){a.getObject()},
1)},remote:function(){for(var a=[this.toElement()],b=0,c=arguments.length;b<c;b++)a.push(arguments[b]);return e.remote.apply(e,a)}});e.getVersion=function(){var a=navigator;if(a.plugins&&a.mimeTypes.length){var b=a.plugins["Shockwave Flash"];if(b&&b.description)return b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0"}else if(c.ActiveXObject&&!c.opera)for(a=10;2<=a;a--)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+a))return b.GetVariable("$version").replace(/WIN/g,
"").replace(/,/g,".")}catch(d){}};a.ui.swf=e})(G,jQuery,window);
G.ui.drag=function(){function a(a){a.stopPropagation();a.preventDefault();if(c&&d){var b=$(window).scrollLeft(),k=$(window).scrollTop(),q=e+a.clientX+b;a=f+a.clientY+k;q=Math.min(Math.max(q,b),$(window).width()-$(c).outerWidth()+b);a=Math.min(Math.max(a,k),$(window).height()-$(c).outerHeight()+k);0>q&&(q=0);0>a&&(a=0);$(c).css("position");$(c).offset({left:q,top:a});h=q;g=a}}function b(a){if(d){a=d&&d.setCapture?d:document;$(a).unbind("mousemove.moving");$(a).unbind("mouseup.stop");"function"==typeof k.onstop&&
k.onstop.apply(d);if(k.fixed&&!1!==h&&!1!==g){var b=$(window).scrollLeft(),n=$(window).scrollTop();$(c).fixedPosition({fixedTo:"top",fixedTop:g<n?0:g-n,fixedLeft:h<b?0:h-b})}d=c=null;f=e=0;if(a.releaseCapture)a.releaseCapture();else if(window.releaseEvents||document.releaseEvents)(window.releaseEvents||document.releaseEvents)(Event.MouseMove|Event.MouseUp)}}var c=null,d=null,e=0,f=0,h=!1,g=!1,k={};return{enable:function(l,m,n){"string"==typeof m&&(m=$("#"+m).get(0));"string"==typeof l&&(m||(m=$("#"+
l+"_head").get(0)),l=$("#"+l).get(0));l&&m&&(k=n||{},$(m).mousedown(function(k){c=l;d=m;k.stopPropagation();k.preventDefault();if(c&&d){var n=$(window).scrollLeft(),p=$(window).scrollTop();e=c.offsetLeft-k.clientX-n;f=c.offsetTop-k.clientY-p;"fixed"==$(c).css("position")&&(e+=n,f+=p);g=h=!1;k=d&&d.setCapture?d:document;$(k).bind("mousemove.moving",a).bind("mouseup.stop",b);if(k.setCapture)k.setCapture();else if(window.captureEvents||document.captureEvents)(window.captureEvents||document.captureEvents)(Event.MouseMove|
Event.MouseUp)}}))}}}();G.ui.droplist={attach:function(){}};
G.ui.modal=function(){return{create:function(a,b){var c=null;a?(c=$('<iframe style="z-index:-1;width:'+$(a).innerWidth()+"px;height:"+$(a).innerHeight()+'px" src="javascript:void(0)" frameborder="0" scrolling="no" width="100%" height="100%"></iframe>').css({opacity:0,background:"#FFF",left:"0",top:"0",position:"absolute"}),c.appendTo(a)):(c=$('<iframe src="javascript:void(0)"></iframe>').css({opacity:0,background:"#000",left:"0",display:"none",zIndex:1100,top:"0",position:"absolute"}),c.css({width:$(window).width()+
"px",height:$(window).height()+"px"}),c.appendTo($("body")).show(),b?c.fixedPosition({fixedTo:"top",fixedTop:0,fixedLeft:0}):c.css({left:$(window).scrollLeft(),top:$(window).scrollTop()}));return c}}}();
G.ui.popup={_cssLoaded:!1,_loadCss:function(){if(!this._cssLoaded){this._cssLoaded=!0;var a=G.prefix.st+"static_v1/css/package/package_v1.css";G.prefix.ssl&&(a=G.prefix.st_ssl+"static_v1/css/package/package_v1.css");var b=!1;$("link").each(function(){if($(this).attr("href")==a)return b=!0,!1});b||$('<link href="'+a+'" rel="stylesheet" type="text/css" charset="utf-8" />').appendTo($("head"))}},_zIndex:1101,create:function(a){function b(a,b){null==a&&(a=g.width());null==b&&(b=g.height());var c=$(window).width(),
d=$(window).height(),c=f.fullscreen&&c<a?0:c/2-a/2,d=f.fullscreen&&d<b?0:d/2-b/2;g.ifFixedPosition()?g.fixedPosition({fixedTo:"top",fixedLeft:c,fixedTop:d}):(g.css("left",$(window).scrollLeft()+c+"px"),g.css("top",$(window).scrollTop()+d+"px"));f.fullscreen&&!g.mDiv&&(d=$("<div></div>").css({opacity:0.05,background:"#000",display:"none",zIndex:1101,width:$(window).width()+"px",height:$(window).height()+"px"}).appendTo("body"),g.ifFixedPosition()?d.fixedPosition({fixedTo:"top",fixedLeft:0,fixedTop:0}):
d.css({left:$(window).scrollLeft(),top:$(window).scrollTop(),position:"absolute"}),d.show(),g.ifFixedPosition()||($.browser.msie?$("html").css({overflow:"hidden"}):$("body").css({overflow:"hidden"})),g.mDiv=d);$.browser.msie&&(6<=$.browser.version&&!g.mIframe)&&(g.mIframe=G.ui.modal.create(f.fullscreen?null:g,g.ifFixedPosition()))}function c(a){f.fullscreen&&g.mDiv&&(g.mDiv.remove(),g.mDiv=null,g.mIframe&&(g.mIframe.remove(),g.mIframe=null),g.ifFixedPosition()||($.browser.msie?$("html").css({overflow:"scroll",
"overflow-x":"hidden"}):$("body").css({overflow:"scroll","overflow-x":"hidden"})));!1!==a&&$.isFunction(f.closeFn)&&f.closeFn.apply(null);g.hide()}this._loadCss();var d=null,e=null,f=a||{},h=50<f.height;f.width=f.width||500;f.fixed=!1===f.fixed?!1:!0;var g=$('<div style="box-shadow:2px 2px 4px rgba(0, 0, 0, 0.5);z-index:'+ ++this._zIndex+";"+(h?"height:"+f.height+"px":"")+";width:"+f.width+'px;" class="layer_global"><div class="layer_global_main"><div class="layer_global_title"><h3><span class="jian">&gt;</span>'+
(f.title||"温馨提示")+'<span></span></h3><button title="关闭" ytag="84777"><span class="none">\ufffd</span></button></div><div class="layer_global_cont layer_cont_15"></div></div></div>');g.appendTo($("body"));f.fixed&&g.fixedPosition({fixedTo:"top"});d=g.find(".layer_global_main .layer_global_title")[0];e=g.find(".layer_global_main .layer_global_cont")[0];"30"==a.contWidth&&$(e).removeClass("layer_cont_15").addClass("layer_cont_30");$(d).children("button").click(c);!f.disableDrag&&G.ui.drag.enable(g.get(0),
d,{fixed:g.ifFixedPosition()});h?b(f.width,h?f.height:300):c();return{onclose:function(a){f.closeFn=a},close:c,hide:c,show:function(){g.show();b()},paint:function(a){if($.isFunction(a))return a.apply(g,[{header:d,content:e}])},setAtCenter:b,resize:function(a){$.isPlainObject(a)&&(a.width&&g.css("width",a.width+"px"),50<a.height&&(g.css("height",a.height+"px"),$(e).height(a.height-50)),b())},resizeNoCenter:function(a){$.isPlainObject(a)&&(a.width&&g.css("width",a.width+"px"),50<a.height&&(g.css("height",
a.height+"px"),$(e).height(a.height-50)))}}},_msgPopup:null,showMsg:function(a){var b=arguments,c=b[1]||{};"object"!=$.type(c)&&(c={},$.each({1:"type",2:"okFn",3:"closeFn",4:"cancelFn",5:"okText",6:"cancelText"},function(a,d){null!=b[a]&&(c[d]=b[a])}),c.okText&&c.cancelText&&(c.btns=3));this._msgPopup||(this._msgPopup=G.ui.popup.create({title:"提示",width:500,height:170,fullscreen:1}));var d={1:"warn",2:"error",3:"right"};c.type in d||(c.type=1);$.isArray(a)||(a=[a]);c.btns=c.btns||1;this._msgPopup.paint(function(b){return function(f){$(f.content).empty().html(' <div class="layer_global_mod">\t<b class="icon icon_msg4 icon_msg4_'+
d[c.type]+'"></b>'+(1<=a.length?'<h4 class="layer_global_tit">'+a[0]+"</h4>":"")+"\t"+(2<=a.length?"<p>"+a[1]+"</p>":"")+a.slice(2,a.length).join("")+'\t<div class="wrap_btn"><a class="btn_strong" href="#" onclick="return false">'+(c.okText||"确定")+'</a> <a class="btn_common" href="#" onclick="return false">'+(c.cancelText||"取消")+"</a></div>\t</div>");$(".wrap_btn .btn_strong",f.content).click(function(){var a=!0;$.isFunction(c.okFn)&&(a=!1!==c.okFn());a&&b.hide(!1)})[c.btns&1?"show":"hide"]();$(".wrap_btn .btn_common",
f.content).click(function(){var a=!0;$.isFunction(c.cancelFn)&&(a=!1!==c.cancelFn());a&&b.hide(!1)})[c.btns&2?"show":"hide"]();b.show()}}(this._msgPopup));this._msgPopup.onclose($.isFunction(c.closeFn)?c.closeFn:$.noop);return this._msgPopup}};
(function(a){var b={},c=0,d=null,e=!1;a.fn.ifFixedPosition=function(){return!this.attr("id")||0==this.attr("id").length?!1:!!b[this.attr("id")]};a.fn.fixedPosition=function(f){f=a.extend({fixedTo:"bottom",fixedTop:0,fixedBottom:0,fixedLeft:!1,effect:!1,effectSpeed:1E3},f);return this.each(function(){var h=a(this);(!h.attr("id")||0==h.attr("id").length)&&h.attr("id","positionFixedID"+c++);null===d&&(a('<div style="position: absolute; top: 200px;" class="outer"><div style="position: fixed; top: 100px;" class="inner"></div></div>').appendTo(a("body")),
d=a(".inner").get(0).getBoundingClientRect&&a(".inner").get(0).getBoundingClientRect().top==a(".outer").get(0).getBoundingClientRect().top?!1:!0);if(Boolean(d))h.css("position","fixed"),"top"==f.fixedTo?h.css("top",(f.fixedTop||0)+"px"):h.css("bottom",(f.fixedBottom||0)+"px"),!1!==f.fixedLeft&&h.css("left",f.fixedLeft+"px");else{if(!1===e){var g=a("body"),k="http://st.icson.com/static_v1/img/blank.gif";G.prefix.ssl&&(k=G.prefix.st_ssl+"/static_v1/img/blank.gif");"none"==g.css("background-image")?
g.css({"background-image":"url("+k+")","background-attachment":"fixed"}):g.css("background-attachment","fixed");e=!0}g="";"top"==f.fixedTo?(g="$(document).scrollTop()",0<f.fixedTop&&(g+="+"+f.fixedTop)):(g='$(document).scrollTop() - $("#'+h.attr("id")+'").outerHeight() + (document.documentElement.clientHeight || document.body.clientHeight)',0<f.fixedBottom&&(g+="-"+f.fixedBottom));h.css("position","absolute");0<h.length&&h[0].style&&h[0].style.setExpression?h[0].style.setExpression("top","eval("+
g+")"):h.css("top",(f.fixedTop||0)+"px");!1!==f.fixedLeft&&h.css("left",a(document).scrollLeft()+(f.fixedLeft-0)+"px")}b[a(this).attr("id")]=1;if(f.effect)switch(f.effect){case "fadeIn":h.hide().fadeIn(f.effectSpeed);break;case "slideDown":h.hide().slideDown(f.effectSpeed)}})}})(jQuery);
G.ui.template={fillWithTPL:function(a,b,c,d,e){if(b){!c&&!1!==c&&(c=a+"_tpl");d=!1===c?d||"":$("#"+c).html().replace(/^\s*\x3c!--/,"").replace(/--\x3e\s*$/,"");var f={};d=d.replace(/<@([0-9a-zA-Z_-]+)@>((.|\s)*?)<@_\1@>/g,function(a,b,c){f[b]=c;return"[#"+b+"#]"});$.each(f,function(a,c){var d=[],e=b[a];e&&$.each(e,function(a,b){d.push(G.ui.template.fillWithTPL(!1,b,!1,c.replace(/<_index_>/g,a-0+1)))});f[a]=d.join("")});c=d.replace(/\{([0-9a-zA-Z_-]+)\}/g,function(a,c){return void 0!==b[c]?b[c]:""}).replace(/\[#([0-9a-zA-Z_-]+)#\]/g,
function(a,b){return void 0!==f[b]?f[b]:b}).replace(/^\s+/,"");if(e||!1===a)return c;$("#"+a).html(c)}}};
G.ui.tips={err:function(a,b,c){this._set(a,2,b,c)},info:function(a,b,c){this._set(a,0,b,c)},warn:function(a,b,c){this._set(a,1,b,c)},suc:function(a,b,c){this._set(a,3,b,c)},help:function(a,b,c){this._set(a,4,b,c)},none:function(a,b){this._set(!1,0,a,b)},_set:function(a,b,c,d){d=$.extend({autoHide:!0,style:""},d||{});"inner"!=d.style&&"bigtop"!=d.style&&(d.style="");var e="tips"+d.style,f="tipstimeout"+d.style;$(c).data(f)&&(clearTimeout($(c).data(f)),$(c).removeData(f));var h=$(c).data(e),g="bigtop"==
d.style?"big":"";if(!h||0==h.parent().length)h=$(G.logic.constants.getTipStr(a,b,!1,g)),$(c).data(e,h),"inner"==d.style?c.empty().append(h):"bigtop"==d.style?h.insertBefore(c):h.insertAfter(c);h.hide();if(!1!==a){if(null==b||!(b in G.logic.constants.tipsLevel))b=0;e="";e="bigtop"==d.style?"para_blo para_"+G.logic.constants.tipsLevel[b]+" cart_tip":"para_inb para_"+G.logic.constants.tipsLevel[b];h.empty().html(G.logic.constants.getTipStr(a,b,!0,g)).removeClass().addClass(e).fadeIn(200);d.autoHide&&
$(c).data(f,setTimeout(function(){h&&h.fadeOut(200)},"boolean"==$.type(d.autoHide)?5E3:d.autoHide))}},_setCart:function(a,b,c,d){d=$.extend({autoHide:!0,style:""},d||{});"inner"!=d.style&&"bigtop"!=d.style&&(d.style="");var e="tips"+d.style,f="tipstimeout"+d.style;$(c).data(f)&&(clearTimeout($(c).data(f)),$(c).removeData(f));var h=$(c).data(e),g="bigtop"==d.style?"big":"";if(!h||0==h.parent().length)h=$(G.logic.constants.getTipStr_cart(a,b,!1,g)),$(c).data(e,h),"inner"==d.style?c.empty().append(h):
"bigtop"==d.style?h.insertBefore(c):h.insertAfter(c);h.hide();if(!1!==a){if(null==b||!(b in G.logic.constants.tipsLevel))b=0;e="";e="bigtop"==d.style?"para_blo para_"+G.logic.constants.tipsLevel[b]+" cart_tip":"para_inb para_"+G.logic.constants.tipsLevel[b];h.empty().html(G.logic.constants.getTipStr_cart(a,b,!0,g)).removeClass().addClass(e).fadeIn(200);d.autoHide&&$(c).data(f,setTimeout(function(){h&&h.fadeOut(1E4)},"boolean"==$.type(d.autoHide)?5E3:d.autoHide))}},setLoading:function(a){},unsetLoading:function(a){},
swapInput:function(a){if(!a||!a.target)return null;a.defaultValue=a.defaultValue||"";a.focusClass=a.focusClass||"";a.blurClass=a.blurClass||"";$(a.target).focus({opt:a},function(a){var c=$(this).val();(c==a.data.opt.defaultValue||""==c)&&$(this).val("");$(this).removeClass(a.data.opt.blurClass).addClass(a.data.opt.focusClass);0<=c.indexOf(a.data.opt.defaultValue)&&$(this).val(c.replace(a.data.opt.defaultValue,""))}).blur({opt:a},function(a){var c=$(this).val();c==a.data.opt.defaultValue||""==c?$(this).val(a.data.opt.defaultValue).removeClass(a.data.opt.focusClass).addClass(a.data.opt.blurClass):
$(this).removeClass(a.data.opt.blurClass).addClass(a.data.opt.focusClass);0<=c.indexOf(a.data.opt.defaultValue)&&$(this).val(c.replace(a.data.opt.defaultValue,""))});$(a.target).blur();return $(a.target)}};
G.ui.page=function(a,b,c,d){a+="";b-=0;c-=0;d=d||3;if(2>c)return"";var e=b-d;d=b+d;str="";4>=e&&(e=2);e=1<e?e:2;d=d<c?d<b?b:d:c-1;var f="",f=0==a.indexOf("javascript:")?' href="#" onclick="'+a.substr(11)+';return false"':' href="'+a+'"';str+=1==b?'<span class="page-start"><b>&lt;</b>上一页</span>':"<a"+f.replace(/\{page\}/g,b-1)+' class="page-prev"><b>&lt;</b>上一页</a>';str+=1==b?'<span class="page-this">1</span>':"<a"+f.replace(/\{page\}/g,1)+">1</a>";for(2!=e&&(str+='<span class="page-break">...</span>');e<
d+1;e++)str=e==b?str+('<span class="page-this">'+b+"</span>"):str+("<a"+f.replace(/\{page\}/g,e)+">"+e+"</a>");d!=c-1&&(str+='<span class="page-break">...</span>');str+=b!=c?"<a"+f.replace(/\{page\}/g,c)+">"+c+"</a>":'<span class="page-this">'+c+"</span>";str+=b!=c?"<a"+f.replace(/\{page\}/g,b+1)+' class="page-next">下一页<b>&gt;</b></a>':'<span class="page-end">下一页<b>&gt;</b></span>';a=0==a.indexOf("javascript:")?"$.globalEval('"+a.substr(11).replace(/'/g,"\\'").replace(/\{page\}/g,"'+a+'")+"')":"location.href='"+
a.replace(/'/g,"\\'").replace(/\{page\}/g,"'+a+'")+"'";return str+='<span class="page-skip"> 到第<input type="text" value="'+b+'" maxlength="3" name="iptpage" onkeydown="if(event.keyCode==13){$(\'button[name=go]\',$(this).parent()).click();return false;}">页<button name="go" value="go" onclick="'+("var a=parseInt($('input[name=iptpage]',$(this).parent()).val(),10);a=(!!a&&a>0&&a<="+c+")?a:1;"+a+";")+'return false">确定</button></span>'};
G.logic.constants={userLevelName:{"0":"土星会员",1:"铜盾会员",2:"银盾会员",3:"金盾会员",4:"钻石会员",5:"皇冠会员",6:"易金鲸"},getSmallUrl:function(a,b){return this._getPicUrl(a,"small",b)},getSSUrl:function(a,b){return this._getPicUrl(a,"ss",b)},getMMUrl:function(a,b){return this._getPicUrl(a,"mm",b)},getMiddleUrl:function(a,b){return this._getPicUrl(a,"middle",b)},getBigUrl:function(a,b){return this._getPicUrl(a,"mpic",b)},getPic160Url:function(a,b){return this._getPicUrl(a,"pic160",b)},getPic60Url:function(a,b){return this._getPicUrl(a,
"pic60",b)},getPic200Url:function(a,b){return this._getPicUrl(a,"pic200",b)},getBigUrl:function(a,b){return this._getPicUrl(a,"mpic",b)},_getPicUrl:function(a,b,c){var d=a.split("R",2);a=d[0];var d=a.split("-",3),e=d[0],f=d[1];return"http://img"+(parseInt(d[2])%2?"1":"2")+".icson.com/product/"+b+"/"+e+"/"+f+"/"+a+(0==c?"":"-"+(10>c?"0"+c:c))+".jpg"},picHandler:function(){var a;a={getPicUrl:function(a,c,d){var e=a.split("R",2);a=e[0];var e=a.split("-",3),f=e[0],h=e[1];return"http://img"+(parseInt(e[2])%
2?"1":"2")+".icson.com/product/"+c+"/"+f+"/"+h+"/"+a+(0==d?"":"-"+(10>d?"0"+d:d))+".jpg"},getPicByPic:function(a,c){return 0==c?(a+"").replace(/(jpg|gif|png|bmp)\/\d+(\?\w+)?$/,"$1/"+c+"$2").replace(/qqbuy/,"51buypic"):(a+"").replace(/(jpg|gif|png|bmp)\/\d+(\?\w+)?$/,"$1/"+c+"$2")},getYXPicBySize:function(a,c){var d=[0,30,60,80,120,160,200,300,400,600,800];-1<a.indexOf("icson.com")&&(d=[50,60,80,120,160,200,300,600,800]);for(var e=!1,f=0;f<d.length;f++)if(c==d[f]){e=!0;break}return e?(d=a,-1<a.indexOf("wgimg.com")?
d=this.getPicByPic(a,800==c?0:c):-1<a.indexOf("paipaiimg.com")?d=a.replace(/(\.)\d+x\d+(\.jpg|gif|png|bmp)?$/,"$1"+(c+"x"+c)+"$2"):-1<a.indexOf("icson.com")&&(d=a.replace(/\/product\/\w+\//,"/product/"+this.icsonExistMap[""+c]+"/")),d):d.join(",")},getIcsonPicBySize:function(a,c,d){var e=this.icsonExistMap;if(""+d in e)return this.getPicUrl(a,e[""+d],c);a=[];for(var f in e)a.push(f);return a.join(",")},icsonExistMap:{50:"ss",60:"pic60",80:"small",120:"middle",160:"pic160",200:"pic200",300:"mm",800:"mpic"}};
return{getPicBySize:function(){if(2==arguments.length)return a.getYXPicBySize.apply(a,arguments);if(3==arguments.length)return a.getIcsonPicBySize.apply(a,arguments)}}}(),tipsLevel:{"0":"info",1:"warn",2:"error",3:"right",4:"help"},getTipStr:function(a,b,c,d){if(null==a)return"";if(null==b||!(b in G.logic.constants.tipsLevel))b=0;if(0==b||4==b)b=1;b=G.logic.constants.tipsLevel[b];var e="";if("big"==d){"array"!=$.type(a)&&(a=[a]);var f=[];1<a.length&&(d=a.shift(),$.each(a,function(a,b){f.push("<p>"+
b+"</p>")}),a.unshift(d));f=0<f.length?'<div class="bd">'+f.join("")+"</div>":"";e='<div class="inner"> <b class="icon icon_msg3 icon_msg3_'+b+'"></b><div class="hd"><strong class="tit">'+(0<a.length?a[0]:"")+"</strong></div>"+f+"</div>";e=c?e:'<div class="para_blo para_'+b+'">'+e+"</div>"}else e='<b class="icon icon_msg0 icon_msg0_'+b+'"></b><span class="para_tit">'+a+"</span>",e=c?e:'<p class="para_inb para_'+b+'">'+e+"</p>";return e},getTipStr_cart:function(a,b,c,d){if(null==a)return"";if(null==
b||!(b in G.logic.constants.tipsLevel))b=0;if(0==b||4==b)b=1;b=G.logic.constants.tipsLevel[b];var e="";if("big"==d){"array"!=$.type(a)&&(a=[a]);var f=[];1<a.length&&(d=a.shift(),$.each(a,function(a,b){f.push("<p>"+b+"</p>")}),a.unshift(d));f=0<f.length?f.join(""):"";e='<div class="inner"> <b class="icon icon_msg3 icon_msg3_'+b+'"></b><div class="hd"><strong class="tit">'+(0<a.length?a[0]:"")+"</strong></div>"+f+"</div>";e=c?e:'<div class="para_blo para_'+b+'">'+e+"</div>"}else e='<b class="icon icon_msg0 icon_msg0_'+
b+'"></b><span class="para_tit">'+a+"</span>",e=c?e:'<p class="para_inb para_'+b+'">'+e+"</p>";return e},goToCart:function(a,b,c){a&&(c=$(c).attr("ytag")||$(c).attr("YTAG")||"",0==window.yPageId&&0==window.yPageLevel?c="":c&&(c=window.yPageLevel+"."+window.yPageId+""+c),G.util.cookie.add("backurl",location.href,"/",0,"."+G.domain),"object"==typeof a?0<a.pid&&(location.href="http://buy."+G.domain+"/cart.html?"+((a.isPackage&&1==a.isPackage?"pkgid=":"pid=")+a.pid)+"&pnum="+(a.pnum||1)+(a.isPackage&&
1==a.isPackage?"":"&mid="+(a.mid||a.pid))+(a.price_id&&0<a.price_id?"&price_id="+a.price_id:"")+(0!=b?"&ism="+b:"")+(c?"&ytag="+c:"")):location.href="http://buy."+G.domain+"/cart.html?ids="+a+(1==b?"&ism=1":"")+(c?"&ytag="+c:""))},goToCartWithThis:function(a,b,c){return G.logic.constants.goToCart(b,c,a)},allowedWhInfo:{1:"上海",1001:"深圳",2001:"北京",3001:"武汉",4001:"重庆",5001:"西安"},serviceAreasSeq:"2621 3225 1591 1 403 201 1323 1718 789 556 131 2858 814 1454 1144 2329 2490 1900 1830 999 2212 299 2016 158 2652 3077 693 2996 2130 2160 2878".split(" "),
sh_icson_delivery_city:["2621"],serviceAreas:{2621:["上海","1","2626"],3225:["浙江","1","3227"],1591:["江苏","1","1593"],1:["安徽","1","9"],2130:["宁夏","5001","2132"],2160:["青海","5001","2162"],403:["广东","1001","421"],201:["福建","1001","203"],1718:["江西","3001","1720"],789:["海南","1001","791"],3077:["云南","4001","3079"],556:["广西","1001","601"],2878:["新疆","5001","2880"],2996:["西藏","4001","2998"],131:["北京","2001","3803"],2858:["天津","2001","2860"],814:["河北","2001","816"],1144:["河南","3001","1146"],2329:["山东","2001",
"2331"],2490:["山西","2001","2492"],1900:["辽宁","2001","1902"],1830:["吉林","2001","1832"],999:["黑龙江","2001","1001"],2212:["陕西","5001","2226"],299:["甘肃","5001","302"],2016:["内蒙古","2001","2018"],1454:["湖南","3001","1456"],693:["贵州","4001","695"],1323:["湖北","3001","4046"],158:["重庆","4001","200"],2652:["四川","4001","2654"]},getLocationId:function(){return G.util.cookie.get("prid")||"2626_2621"},setLocationId:function(a){return a?(G.util.cookie.add("prid",a,"/",2592E3,"."+G.domain),!0):!1},getSiteId:function(){return G.util.cookie.get("wsid")||
1},setSiteId:function(a){return a?(G.util.cookie.add("wsid",a,"/",2592E3,"."+G.domain),!0):!1},getProvId:function(){return G.logic.constants.getLocationId().split("_")[1]},categoryAds:{"0":["dh-1big-phone","dh-3small-phone"],1:["dh-1big-digital","dh-3small-digital"],2:["dh-1big-computer","dh-3small-computer"],3:["dh-1big-hardware","dh-3small-hardware"],4:["dh-1big-fujian","dh-3small-fujian"],5:["dh-1big-big_e","dh-3small-big_e"],6:["dh-1big-house_e","dh-3small-house_e"],7:["dh-1big-kitchen","dh-3small-kitchen"],
8:["dh-1big-office","dh-3small-office"],9:["dh-1big-car","dh-3small-car"],10:["dh-1big-bodycare","dh-3small-bodycare"],11:["dh-1big-grocery","dh-3small-grocery"]}};
$.extend(G.logic.constants,{getWhId:function(){var a=G.createFnQueue(),b=0;return function(c){_whId=G.logic.constants.getSiteId();a.add(c);2==b||!1!==_whId?a.exec(_whId):1!=b&&(b=1,$.get("http://"+G.DOMAIN.BASE_ICSON_COM+"/json.php?mod=user&act=getwhid",function(c){b=2;_whId=1;_prId=2621;c&&0==c.errno&&G.logic.constants.allowedWhInfo[c.data]&&(_whId=c.data,_prId=c.prid);G.logic.constants.setSiteId(_whId);G.logic.constants.setLocationId(G.logic.constants.serviceAreas[_prId][2]+"_"+_prId);a.exec(_whId)},
"jsonp"))}}()});
G.logic.validate={checkURL:function(a){return/^(https?:\/\/|ftp:\/\/)?(([a-z0-9\-]*\.)+([a-z]{2}|aero|arpa|biz|com|coop|edu|gov|info|int|jobs|mil|museum|name|nato|net|org|pro|travel)|(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))(\/[a-z0-9_\-\.~]+)*(\/([a-z0-9_\-\.]*)(\?[a-z0-9+_\-\.%=&amp;\/]*)?)?(#[a-z][a-z0-9+_\-\.%=&amp;\/]*)?$/i.test(a)},checkMobilePhone:function(a){return/^((\(\d{3}\))|(\d{3}\-))?1\d{10}$/.test(a)},checkEmail:function(a){return/^[a-z0-9_\-]+(\.[_a-z0-9\-]+)*@([_a-z0-9\-]+\.)+([a-z]{2}|aero|arpa|biz|com|coop|edu|gov|info|int|jobs|mil|museum|name|nato|net|org|pro|travel)$/i.test(a)},checkTelephone:function(a,
b){var c=/^([0-9]{3}|0[0-9]{3})-[1-9][0-9]{6,7}(-[0-9]{1,6})?$/,d=/^[0-9]{4}-([0-9]{3}|0[0-9]{3})-[0-9]{7,8}$/;b=b||3;return 1==(b&1)&&c.test(a)||2==(b&2)&&d.test(a)?!0:!1},checkPhone:function(a){return this.checkTelephone(a)||this.checkMobilePhone(a)},checkNumber:function(a){return/^[1-9]\d*$/.test(a)},checkChars:function(a,b){var c="^[";b=b||7;1==(b&1)&&(c+="一-\u9fa5");2==(b&2)&&(c+="a-zA-Z");4==(b&4)&&(c+="0-9");return RegExp(c+"]*$","").test(a)},checkOrderId:function(a){return a&&10==a.length&&
G.logic.validate.checkNumber(a)},lenMon:function(a){function b(){var b=$(a.target).val(),d=a.charLenStyle?$.strlen(b):b.length,d=b==a.defaultValue?0:d;a.tipCtrl&&($(a.tipCtrl).html("<b>"+d+"</b>/"+a.maxLen),d<a.minLen||d>a.maxLen?$("b",a.tipCtrl).removeClass(a.sucClass).addClass(a.failClass):$("b",a.tipCtrl).removeClass(a.failClass).addClass(a.sucClass))}if(!a||!a.target)return null;a={target:a.target,minLen:a.minLen||0,maxLen:a.maxLen||Infinity,sucClass:a.sucClass||"",failClass:a.failClass||"",defaultValue:a.defaultValue||
"",tipCtrl:a.tipCtrl||null,charLenStyle:a.charLenStyle||!1};b();return $(a.target).keyup(b).bind("paste",b)}};
G.logic.login={_refer:null,_refUrl:"",_loginUser:!1,_loginPopup:!1,_userFnQueue:G.createFnQueue(),_qqloginFnQueue:G.createFnQueue(),_loginFnQueue:G.createFnQueue(!1),_logoutFnQueue:G.createFnQueue(!1),_loginNameCutLen:8,cutString:function(a,b){if(0>=b||a.replace(/[^\x00-\xff]/g,"**").length<=b)return a;for(var c=a;c.replace(/[^\x00-\xff]/g,"**").length>b;)c=c.substr(0,c.length-1);c.length<a.length&&(c+="...");return c},popup:function(a){a="https://base."+G.domain+"/login.html?url="+encodeURIComponent("string"==
typeof a?a:location.href);location.href=a;return!0},login:function(a,b,c,d,e){var f={account:a,password:b};$.each(e||{},function(a,b){f[a]=b});G.util.post("https://"+G.DOMAIN.BASE_ICSON_COM+"/json.php?mod=login&fmt=1",f,function(a){a&&0==a.errno?$.isFunction(c)&&c(a):$.isFunction(d)&&d(a&&a.errno?a.errno:null)})},updateHead:function(){G.logic.constants.getWhId(function(a){G.logic.constants.allowedWhInfo[a]?G.logic.login.getLoginUser(function(a){$("#PageToolbar");var c=$("#PageLoginStatusbar"),d=$("#PageWelcome"),
e=$("#PageMyOrderLi");0<d.length?d.remove():($("#PageLogin").remove(),$("#PageLoginByQQBtn").remove(),$("#PageRegLi").remove());$("#NewUserCoupon").remove();if(a&&0==a.errno){var d=a.data,f="";if(0==d.icsonid.toString().indexOf("Login_QQ_")||"true"===G.util.cookie.get("__BINDQQACCOUNT")){var f='<i class="icon_qq">&nbsp;</i>欢迎您，QQ用户',h=G.util.cookie.get("cps_msg").split("|");if(2<=h.length&&h[0]==d.uid){if(h.shift(),f=G.util.parse.encodeHtml(h.join("|")),"qqcb"==G.util.cookie.get("cps_src")){var g=
'<div class="mod_top_banner"><div class="main_area"><div class="sale_tip"><strong>QQ彩贝联盟商家：</strong>易迅-QQ会员购物成功最高返<span class="redf">4320</span>彩贝积分，普通用户最高返2880彩贝积分<a ytag="06807" href="http://cb.qq.com/get_jifen.html" target="_blank" title="积分详情">(详情)</a></div><div class="login_status"><span class="qqUser login_btn"><span class="name">'+f+'<a ytag="06808" href="http://cb.qq.com/my/my_jifen_source.html" target="_blank" title="我的彩贝积分" class="my_caibei">我的彩贝积分</a></div></div></div>';setTimeout(function(){$("body").prepend(g)},
500)}}else h=G.util.cookie.get("qq_nick").split("|"),2<=h.length&&h[0]==d.uid&&(h.shift(),f+=G.logic.login.cutString(G.util.parse.encodeHtml(h.join("|")),G.logic.login._loginNameCutLen))}else 0==d.icsonid.toString().indexOf("Login_Alipay_")?f=1==parseInt(a.data.status_bits&1)?"欢迎您，支付宝VIP："+G.logic.login.cutString(G.util.parse.encodeHtml(d.name||d.icsonid),G.logic.login._loginNameCutLen)+"，":G.logic.login.cutString(G.util.parse.encodeHtml(d.name||d.icsonid),G.logic.login._loginNameCutLen)+" 您好":/^\d+@51fanli$/.test(d.icsonid.toString())?
(h=G.util.cookie.get("cps_msg").split("|"),2<=h.length&&h[0]==d.uid&&(f=h[1])):f=0==d.icsonid.toString().indexOf("Login_SHAuto_")?"欢迎您，安悦用户："+G.logic.login.cutString(G.util.parse.encodeHtml(d.icsonid.substr(13)),G.logic.login._loginNameCutLen)+" 您好":0==d.icsonid.toString().indexOf("Login_SAND_")?"欢迎您，杉德用户："+G.logic.login.cutString(G.util.parse.encodeHtml(d.icsonid.substr(11)),G.logic.login._loginNameCutLen)+" 您好":"欢迎您，"+G.logic.login.cutString(G.util.parse.encodeHtml(d.icsonid),G.logic.login._loginNameCutLen);
c.prepend('<li id="PageWelcome" class="item"><span class="welcome">'+f+'</span>[<a ytag="06300" href="javascript:;" name="quit" hotName="I.INDEX.HEAD_EXIT" onclick="return false">退出</a>]</li>');c.find("a[name=quit]").click(G.logic.login.logout);e.find("div.mod_order").html("正在加载...");G.logic.login.mouseEnterAndOut(e.find("div.menu"),function(a){"正在加载..."==a.find("div.mod_order").html()&&G.util.post("http://d."+G.domain+"/json.php?mod=index&act=getmyorders&fmt=1",{},function(b){if(b&&("errno"in b&&
"data"in b)&&0==b.errno){if($.isArray(b.data)){var c="",d=6302;if(0<b.data.length){for(var c=c+"<ul>",e=0,f=b.data.length;e<f;e++)var g=b.data[e].order_status,h=0<g.indexOf("作废")?"wait":"",c=c+('<li>\t<div class="pic_wrap">\t\t<a ytag="0'+d++ +'" href="http://item.'+G.domain+"/item-"+b.data[e].product_id+'.html" target="_blank"><img alt="'+b.data[e].product_name+'" src="'+b.data[e].product_img+'"></a>\t</div>\t<div class="order_info">\t\t<dl>\t\t\t<dt><a ytag="0'+d++ +'" href="http://base.'+G.domain+
"/orderdetail-"+b.data[e].order_id+'.html" target="_blank">'+b.data[e].order_id+"</a></dt>\t\t\t<dd>"+b.data[e].order_date+'</dd>\t\t</dl>\t</div>\t<div class="order_status"><span class="'+h+'">'+g+"</span>"+b.data[e].order_delay+"</div></li>");c=c+"</ul>"+('<p class="order_old"><a ytag="06301" title="更早订单" href="http://base.'+G.domain+'/myorder.html?YTAG=1.100000003">更早订单<i class="dot_arrow"></i></a></p>')}else c+="没有记录";a.find("div.mod_order").html(c);return}if("string"==$.type(b.data)){a.find("div.mod_order").html(b.data);
return}}a.find("div.mod_order").html("订单信息加载失败，请您稍后重试")})},null,"menu_hover")}else{d="登录&nbsp;";f="注册&nbsp;";e="https://base."+G.domain+"/register.html";h="";if(location.href.match(/^http:\/\/b\.51buy\.com/)||location.href=="http://event."+G.domain+"/event/478cfee.html"||location.href=="http://event."+G.domain+"/event/4819461.html"||location.href=="http://event."+G.domain+"/event/479d18f.html")d="大客户登录&nbsp;",f="大客户注册&nbsp;",e="http://b."+G.domain+"/retailerreg.html",h=" item_login_distributor";d=
'<li id="PageLogin" class="item'+h+'"><a ytag="06800" href="https://base.'+G.domain+"/login.html?url="+encodeURIComponent(location.href)+'" >'+d+'</a></li><li id="PageLoginByQQBtn" class="item loginbyqq"><a ytag="06805" href="http://3c.buy.qq.com/www/icson/redirect.html?url=http%3A%2F%2Fui.ptlogin2.qq.com%2Fcgi-bin%2Flogin%3Fappid%3D700024506%26s_url%3Dhttp%253A%252F%252F3c.buy.qq.com%252Fwww%252Ficson%252Flogin.html%253Furl%253Dhttp%25253A%25252F%25252Fbase.'+G.domain+'%25252Findex.php%25253Fmod%25253Duser%252526act%25253Dptloginqq%26qlogin_auto_login%3D1%26hide_close_icon%3D1"><i class="dot_qq">&nbsp;</i></a></li><li id="PageRegLi" class="item"><a ytag="06806" id="PageRegBtn" href="'+
e+'">'+f+"</a></li>";c.prepend(d);d=G.util.parse.url();d=d.search.url||d.hash.url||location.href;/^http:\/\/([a-zA-Z0-9_-]+\.|)51buy\.com/.test(d)||(d="");if(G.logic.login._refUrl=d)f="http://base."+G.domain+"/index.php?mod=user&act=ptloginqq&url="+encodeURIComponent(d),f="http://3c.buy.qq.com/www/icson/login.html?url="+encodeURIComponent(f),f="http://ui.ptlogin2.qq.com/cgi-bin/login?appid=700024506&qlogin_auto_login=1&hide_close_icon=1&style=14&pt_logo_14=1&pt_open_appid=1&s_url="+encodeURIComponent(f),
f="http://3c.buy.qq.com/www/icson/redirect.html?url="+encodeURIComponent(f),$("#qqauthlogin").attr("href",f),$("#PageLoginByQQBtn a").attr("href",f),$("#ali_login").attr("href","http://base."+G.domain+"/index.php?mod=user&act=toalipaylogin&url="+encodeURIComponent(d)),$("#PageRegBtn").attr("href",e+"?url="+encodeURIComponent(d)),$("#PageLogin a.menu_hd").attr("href","https://base."+G.domain+"/login.html?url="+encodeURIComponent(d));G.logic.login.bindHeadLoginHandler($("#PageLogin div.menu"));$("#PageMyOrderLi div.mod_order").html('<p class="empty"><a ytag="06807" href="https://base.'+
G.domain+"/login.html?url="+encodeURIComponent(location.href)+'">登录</a>后查看最近的订单信息</p>');G.logic.login.mouseEnterAndOut($("#PageMyOrderLi div.menu"),null,null,"menu_hover")}0==$("#NewUserCoupon").length&&(a&&0==a.errno)&&(0>=a.data.exp_point?(a=G.logic.constants.getSiteId(),G.logic.getAdItem(a,"homepage",function(a){var b=a["newuser-banner"];a=a["newuser-text"];var d=textAdHtml="";"undefined"!==typeof b&&(d='<a ytag="07501" target="_blank" title="'+b[0].content+'" href="'+b[0].url+'"><img alt="" src="'+
b[0].img_wide+'"></a>');"undefined"!==typeof a&&(2<=a.length?(textAdHtml+='<a ytag="07502" target="_blank" class="ico_new" href="'+a[1].url+'">'+a[1].content+"</a>",textAdHtml+='<a ytag="07503" target="_blank" class="ico_lottery" href="'+a[0].url+'">'+a[0].content+"</a>"):textAdHtml+='<a ytag="07502" target="_blank" class="ico_new" href="'+a[0].url+'">'+a[0].content+"</a>");b='<li id="NewUserCoupon" class="item coupon">\t\t\t\t\t\t\t\t\t\t\t\t<div class="info">\t\t\t\t\t\t\t\t\t\t\t\t\t<a ytag="07500" class="hd" href="http://u.'+
G.domain+'/xinren" target="_blank"><i class="dot_coupon"></i><span>新用户专享</span></a>\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="mod_coupon">\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="bg_img">'+d+'</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class="c_link">'+textAdHtml+'</p>\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class="close" title="关闭" href="javascript:void(0);">关闭</a>\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class="layout_arrow_top"> <span class="">◆</span><i>◆</i> </div>\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t</li>';
0==$("#NewUserCoupon").length&&c.prepend(b);$mod_coupon_box=c.find("div.mod_coupon");window.isOnCoupon=!1;c.find("div.info").mouseover(function(){window.isOnCoupon=!0;$mod_coupon_box.show()}).mouseout(function(){window.isOnCoupon=!1;window.setTimeout(function(){window.isOnCoupon||$mod_coupon_box.hide()},500)}).find("a.close").click(function(){$(this).parent().hide()})})):(a='<li id="NewUserCoupon" class="item coupon">\t\t\t\t\t\t\t<div class="info">\t\t\t\t\t\t\t\t<a ytag="07500" class="hd" href="http://vip.'+
G.domain+'/" target="_blank"><i class="dot_coupon"></i><span>会员俱乐部</span></a>\t\t\t\t\t\t\t</div>\t\t\t\t\t\t</li>',0==$("#NewUserCoupon").length&&c.prepend(a)))}):location.replace("http://www."+G.domain+"/")})},mouseEnterAndOut:function(a,b,c,d){var e=null,f=d||"hover";a.hover(function(){e&&(clearTimeout(e),e=null);a.addClass(f);b&&b(a)},function(){e&&(clearTimeout(e),e=null);e=setTimeout(function(){a.removeClass(f);c&&c(a)},300)})},bindHeadLoginHandler:function(a){var b=a.find("div.mod_login_bd dd.item_submit button"),
c=a.find('div.mod_login_bd input[type="text"]'),d=a.find('div.mod_login_bd input[type="password"]'),e=a.find("div.mod_login_bd dd.error");G.logic.login.mouseEnterAndOut(a,null,function(){h();c.val("");d.val("")},"menu_hover");var f=function(a,b){a&&a.addClass("status_error");e.html('<i class="dot_error"></i>'+b).show()},h=function(){c.removeClass("status_error");d.removeClass("status_error");e.hide().html("")},g=function(){var a=$.trim(location.href);G.logic.login._refUrl&&G.logic.login._refUrl!=
a?location.replace(G.logic.login._refUrl):G.logic.login.updateHead()},k=function(a){switch(a){case 66:f(d,"密码错误，请您重新填写");break;case 67:f(c,"该登录帐号不存在");break;default:f(!1,"对不起，登录失败")}};b.click(function(a){h();a=!1;""==$.trim(c.val())?f(c,"请输入您的易迅帐号"):""==$.trim(d.val())?f(d,"请输入您的易迅密码"):a=!0;a&&G.logic.login.login($.trim(c.val()),$.trim(d.val()),g,k)})},getLoginUid:function(){var a=G.util.cookie.get("uid");return G.logic.validate.checkNumber(a)?a:!1},forceFlushUser:function(){var a=Math.random();G.util.cookie.add("randpro",
a,"/",86400,"."+G.domain);return a},_getLoginUser:function(a,b){var c=G.logic.login,d=$.isFunction(a)?a:$.noop,e=c.getLoginUid();if(!1!=c._loginUser&&c._loginUser.data&&c._loginUser.data.uid==e)d(c._loginUser);else if(c._userFnQueue.add(d),!c._userLoading){c._userLoading=!0;d=G.util.cookie.get("randpro");b&&(d=c.forceFlushUser());var f="";""!=G.util.cookie.get("qplus_nick")&&(f="&"+(new Date).getTime());$.ajax({type:"GET",url:G.util.token.addToken("http://"+G.DOMAIN.BASE_ICSON_COM+"/json.php?mod=user&act=profile&uid="+
e+"&r="+d+f,"jq"),success:function(a){c._userLoading=!1;c._userFnQueue.exec(a);c._loginUser=a},dataType:"jsonp",cache:!0,crossDomain:!0})}},_getLoginQQUser:function(a){if(parent)try{if(!0==parent.limitIframeRequest)return}catch(b){}var c="http://3c.buy.qq.com/www/icson/login.html?auto=1&url="+encodeURIComponent("http://base."+G.domain+"/index.php?mod=user&act=ptloginqq&url="+encodeURIComponent("http://st."+G.domain+"/static_v1/htm/loginjump.htm"))+"&furl="+encodeURIComponent("http://st."+G.domain+
"/static_v1/htm/loginjump.htm"),d=$('<iframe src="about:blank" style="display:none"></iframe>');$("body").prepend(d);var e=$.isFunction(a)?a:$.noop;d[0].callback=function(){e();$(this).src="about:blank";$(this).remove();this.callback=null};$.browser.msie&&9>parseInt($.browser.version)?(G.util.post.pIndex=(G.util.post.pIndex||0)+1,d[0].pIndex=G.util.post.pIndex,d[0].ie6callback=function(){this.src=c},d[0].src=location.protocol+"//st."+G.domain+"/static_v1/htm/ie6post.htm"):d[0].src=c;window.limitIframeRequest=
!0},getLoginUser:function(a,b,c){var d=G.logic.login,e=d.getLoginUid();d._refer=null===d._refer?document.referrer:d._refer;e?(d._refer="",d._getLoginUser(a,c)):(e=G.util.cookie.get("cps_info"),!1!==b&&(/^\s*linktech\|\|A100060164/i.test(e)&&2==G.util.cookie.get("QQACCT")||(""!=d._refer&&!/^http:\/\/([a-z0-9]+\.|)51buy\.com/i.test(document.referrer)||!G.util.cookie.get("QQACCT"))&&!e)?(d._qqloginFnQueue.add(a),d._qquserLoading||(d._qquserLoading=!0,d._getLoginQQUser(function(){d.getLoginUser(function(a){d._refer=
"";a&&0==a.errno&&G.util.cookie.add("QQACCT",a.data.icsonid.replace(/^Login_QQ_/i,""),"/",0,"."+G.domain);d._qquserLoading=!1;d._qqloginFnQueue.exec(a)},!1,c)}))):(d._refer="",$.isFunction(a)&&a(!1)))},logout:function(a){G.util.cookie.get("wg_skey")&&($.ajax({type:"GET",url:"http://base.'+G.domain+'/json.php?mod=user&act=logout&callback=success",success:function(a){G.logic.login.updateHead()},dataType:"jsonp",cache:!0,crossDomain:!0}),G.util.cookie.del("wg_skey","."+G.domain));$.ajax({type:"GET",
url:"http://user.buy.qq.com/cgi-bin/userlogin/logout?callback=success&g_tk="+G.util._DJB(G.util.cookie.get("ptskey"))+"&g_ty=ls",success:function(a){G.logic.login.updateHead()},dataType:"jsonp",cache:!1,crossDomain:!0});G.util.cookie.del("skey","."+G.domain);G.util.cookie.del("ptskey","."+G.domain);G.util.cookie.del("uid","."+G.domain);G.util.cookie.del("qq_nick","."+G.domain);G.util.cookie.del("cps_src","."+G.domain);G.util.cookie.del("BOUND_QQACCT","."+G.domain);G.util.cookie.del("__BINDQQACCOUNT",
"."+G.domain);G.logic.login._logoutFnQueue.exec();$.isFunction(a)&&a();window.LOGIN_NO_JUMP?location.replace(!0===LOGIN_NO_JUMP?"http://www."+G.domain+"/":LOGIN_NO_JUMP):(G.logic.login.updateHead(),G.logic.header.getShoppingCart())},onlogout:function(a){$.isFunction(a)&&G.logic.login._logoutFnQueue.add(a)},ifLogin:function(a,b){return!G.logic.login.getLoginUid()?(G.logic.login.popup(a&&b?function(b){return function(){for(var d=[],e=b.length-1;0<=e;e--)d.unshift(b[e]);b.callee.apply(a,d)}}(b):$.noop),
!1):!0},ifLoginJump:function(){if(!G.logic.login.getLoginUid()){var a="http://www."+G.domain+"/";window.skipJumpPage||(a="https://base."+G.domain+"/login.html?url="+encodeURIComponent(location.href));location.replace(a);return!1}return!0},jump:function(){}};
G.logic.header={_Q_SHOW_DEF_TEXT:"输入品牌或商品进行搜索",loginStatus:function(){G.logic.login.updateHead();G.ui.tips.swapInput({target:$("#q_show"),defaultValue:G.logic.header._Q_SHOW_DEF_TEXT,focusClass:"mod_search_txt",blurClass:"mod_search_txt no_cur"});$.browser.msie&&6==$.browser.version&&$("#q_show").next().click(function(){G.logic.header.query()&&$(this).parents("form")[0].submit()});this.category.init();this.getShoppingCart();this.ga();this.recordLs();this.autoComplete();this.updateQQBuyEntry();this.initTopNotice()},
setBust:function(){if(window.top!==window.self)try{window.top.location.host||this.bust()}catch(a){this.bust()}},bust:function(){document.write="";"admin.icson.com"!=location.host&&(window.top.location=window.self.location,setTimeout(function(){document.body.innerHTML=""},0),window.self.onload=function(a){document.body.innerHTML=""})},updateQQBuyEntry:function(){var a=$("#QQBuyEntry"),b=['<li class="item"><a ytag="07101" target="_blank" href="http://buy.qq.com?WGTAG=1000.24.1.1">QQ网购&nbsp;</a></li><li class="item"><a ytag="07102" target="_blank" href="http://www.paipai.com?ptag=10126.11.1">拍拍&nbsp;</a></li>',
'<li class="item current"><a ytag="07104" target="_blank" href="http://www.'+G.domain+'">易迅&nbsp;</a></li>'].join("");a.append(b)},updateQQBuyEntryZhai:function(){var a=$("#QQBuyEntry");if(!(a.html()||"").match("QQ网购")){var b=['<li class="item"><a ytag="07101" target="_blank" href="http://buy.qq.com?WGTAG=1000.24.1.1">QQ网购&nbsp;</a></li><li class="item"><a ytag="07102" target="_blank" href="http://www.paipai.com?ptag=10126.11.1">拍拍&nbsp;</a></li>','<li class="item current"><a ytag="07104" target="_blank" href="http://www.'+
G.domain+'">易迅&nbsp;</a></li>'].join("");a.append(b)}},recordLs:function(){var a=G.util.parse.url();$.each(a,function(a,c){$.each(c,function(a,b){a=(a+"").toLowerCase();("ls"==a||"us"==a)&&G.util.cookie.add(a,b,"/",604800,"."+G.domain)})})},autoComplete:function(){$(function(){G.logic.constants.getWhId(function(a){function b(){for(var a=G.util.cookie.get("visitkey"),b=G.util.cookie.get("uid"),h={1:"4",1001:"10",2001:"13",3001:"42",4001:"43",5001:"44"}[G.util.cookie.get("wsid")],g=1030,k=0,l=$("#q_show").val(),
m,n,q=0,t=d.length;q<t;q++)l==d[q].value&&(k=q+1);0<k?(g=1027,$("#as").val(2),m=encodeURIComponent(c),n=encodeURIComponent(l)):0==k&&(m=encodeURIComponent(l),n=t);$.getScript("http://search.paipai.com/cgi-bin/clicklog?srcid="+h+"&uin="+b+"&ls="+g+"&subls="+k+"&visitKey="+a+"&ref="+m+"&herf="+n)}a=G.util.cookie.get("wsid");(document.charset||document.characterSet||"").toLowerCase();a=G.ui.autoComplete({target:"#q_show",listOnClass:"autocomplete_status_on",itemActiveClass:"status_on",itemTPL:"<li><span>{label}</span><cite>约{count}个搜索结果</cite></li>",
url:"http://search.paipai.com/cgi-bin/isuggest_yixun?AreaCode="+a+"&charset=utf-8&rcharset=gbk",keyName:"KeyWord",delayTime:250,cache:!0});var c,d=[];a.bind("success",function(a,b){var h=b.response,g=[];if(h&&h.list&&0<h.list.length){c=h.hotclass[0][0];for(var k=0,l=h.list.length;k<l;k++){var m=h.list[k];g.push({value:m[0],count:m[1],label:m[0]})}}d=b.response=g});a.bind("complete",function(){b();$("#q_show").parents("form").submit()});a.bind("enter.autocomplete",function(){b()});$("#q_show").parents("form").children(".search_submit").click(function(){$("#q_show").val()&&
$("#q_show").val()!=G.logic.header._Q_SHOW_DEF_TEXT&&b()})})})},_kefuLink:{1:"http://b.qq.com/webc.htm?new=0&sid=4006401878&eid=218808P8z8p8y8x8Q8R8K&o=http://www."+G.domain+"&q=7",1001:"http://b.qq.com/webc.htm?new=0&sid=4008286699&eid=218808P8z8p8x8z8y8x8z&o=http://www."+G.domain+"&q=7",2001:"http://b.qq.com/webc.htm?new=0&sid=4008280055&eid=218808P8z8p8P8q8R8q8p&o=http://www."+G.domain+"&q=7",3001:"http://b.qq.com/webc.htm?new=0&sid=4008280055&eid=218808P8z8p8P8q8R8q8p&o=http://www."+G.domain+
"&q=7",4001:"http://b.qq.com/webc.htm?new=0&sid=4008286699&eid=218808P8z8p8x8z8y8x8z&o=http://www."+G.domain+"&q=7",5001:"http://b.qq.com/webc.htm?new=0&sid=4008286699&eid=218808P8z8p8x8z8y8x8z&o=http://www."+G.domain+"&q=7"},locateRegion:function(){var a=$("#i_region");if(0!==a.length){var b=arguments.callee,c=G.logic.constants;c.getWhId(function(d){var e=G.logic.constants.getProvId();(d=c.serviceAreas[e][0])?a.html('<p class="trans_to"><span class="trans">送至</span><a href="#" class="change"><span>'+
d+'</span><span class="dot_change"></span></a></p>'):a.html('<p class="trans_to"><span class="trans">送至</span><a href="#" class="change"><span>上海</span><span class="dot_change"></span></a></p>');var f="",h="",g=[],k=1E3;$.each(G.logic.constants.allowedWhInfo,function(a,b){for(var c='<div class="city_item"><div class="storage_item"><p>'+b+"仓服务：</p><ul>",d=0;31>d;d++){var t=G.logic.constants.serviceAreasSeq[d],p=G.logic.constants.serviceAreas[t];a==p[1]&&(f=e==t?'class="current"':"",h=e==t?"":'alt="前往'+
p[0]+'" title="前往'+p[0]+'"',k++,c+='<li><a ytag="0'+k+'"'+h+' href="#" '+f+' onclick="return false" w="'+a+'" p="'+t+'">'+p[0]+"</a></li>")}g.push(c+"</ul></div></div>")});d=$('<div class="jump_city">\t\t\t\t\t<div class="city">'+g.join("")+'<p class="tip">易迅商品暂时只支持配送至中国大陆地区</p></div>\t\t\t\t\t<p class="load"></p>\t\t\t\t\t<p class="f"><span class="icon icon_msg0 icon_msg0_warn"></span>切换失败，请<a class="switch_fail_btn" href="#">返回重试</a></p>\t\t\t\t\t</div>').appendTo(a);G.logic.login.mouseEnterAndOut(a,
null,null,"area_change_hover");$("div.city li a",d).click(function(){b.lastClickDom=this;G.logic.constants.serviceAreas[$(this).attr("p")]&&$(this).attr("p")!=e&&(G.logic.header.switchSite($(this).attr("w"),$(this).attr("p")),G.logic.constants.setLocationId(G.logic.constants.serviceAreas[$(this).attr("p")][2]+"_"+$(this).attr("p")))});$("a.switch_fail_btn",d).click(function(){b.lastClickDom&&$(b.lastClickDom).triggerHandler("click");return!1})})}},switchSite:function(a,b){a=parseInt(a);b=parseInt(b);
var c=arguments.callee,d=G.logic.constants.serviceAreas[b][0];this.xhr||(c.xhr=$.ajax({type:"GET",timeout:3E4,scriptCharset:"gb2312",url:"http://st.icson.com/static_v1/js/app/switchSite.js?v=4.0",dataType:"script",cache:!0,crossDomain:!0}));var e=$("#i_region");c.xhr.done(function(){G.app.switchSite.tryToSwitchTo(a,location.href)}).fail(function(){e.find(".load").css("display","none");e.find(".f").css("display","block");e.find(".close").css("display","block")});e.find(".load").html('<span class="loading_82_21"></span>正在切换到<span class="where">'+
d+"</span>……").css("display","block");e.find(".city, .nor, .f, .close").css("display","none")},ga:function(){var a=a||[],b={1:"UA-10104379-19",1001:"UA-10104379-17",2001:"UA-10104379-18"};window._gaq=a;G.logic.constants.getWhId(function(a){window._gaq.push(["_setAccount","UA-10104379-15"]);window._gaq.push(["_setCustomVar",1,"site_id","site_"+a,2]);window._gaq.push(["_trackPageview"]);window._gaq.push(["_setAccount",b[a]]);window._gaq.push(["_deleteCustomVar",1]);window._gaq.push(["_trackPageview"])})},
query:function(){var a=$("#q_show"),b=$.trim(a.val()),c=!0,d=a.attr("_href");if(b===G.logic.header._Q_SHOW_DEF_TEXT&&d)window.location.href=d,c=!1;else if(""===b||b===G.logic.header._Q_SHOW_DEF_TEXT)a.focus(),c=!1;0===$("#q_show").parents("form").find('input[name="YTAG"]').length&&(a=(window.yPageLevel||0)+"."+(window.yPageId||0)+"02000",$("#q_show").parents("form").append($('<input type="hidden" name="YTAG" value="'+a+'" />')));return c},getHotKey:function(){var a=$("#i_keyword");if(0!==a.length){var b=
"";""!=G.util.cookie.get("qplus_nick")&&(b="&"+(new Date).getTime());G.logic.constants.getWhId(function(c){$.ajax({type:"GET",url:"http://d."+G.domain+"/json.php?mod=hotkey&act=page"+b,success:function(b){b&&0==b.errno&&a.html(b.data)},dataType:"jsonp",cache:!0,crossDomain:!0,scriptCharset:"gb2312",jsonpCallback:"loadSiteHotKey_"+c})})}},getShoppingCart:function(){var a=$("#i_cart_info");if(0!=a.length){var b=G.logic.login.getLoginUid(),c=0,d,e=!1,f=function(b){c=b;d=0==b?" cart_wrap_empty":"";a.html('<a ytag="04700" id="J_cartInfo_a" class="cart_wrap'+
d+'"href="http://buy.'+G.domain+'/cart.html"><i class="dot_cart"></i><span>购物车（'+b+'）件</span></a><div class="cart_list" style="display:none">正在努力为您加载购物车信息…</div>').mouseenter(function(a){a=$("div.cart_list",this);a.show();h(a)}).mouseleave(function(a){0==c&&$("#J_cartInfo_a").addClass("cart_wrap_empty");$("div.cart_list",this).hide()})},h=function(a){if(0!=c){a.css({width:null});var d=G.logic.constants.getLocationId().split("_")[1]||2621,f=29;$.each(G.logic.constants.sh_icson_delivery_city||{},function(a,
b){b==d&&(f=99)});var h='<ul><@rows@><li><div class="pic_wrap"><a ytag="0{ytag1}" href="{product_url}" target="_blank"><img alt="{product_name}" src="{product_img}"></a></div><div class="txt_wrap"><div class="name"><a ytag="0{ytag2}" href="{product_url}" target="_blank">{product_name}</a></div><div class="action"><span class="rmb">&yen;</span><span class="price">{product_price}</span><span class="ride">x</span>{product_count}</div></div></li><@_rows@><dl><dt>共<span class="rmb">{total_count}</span>件商品总计：<span class="rmb">&yen;</span><span class="price">{total_price}</span></dt>'+
('<dd class="fee_tip">满'+f+"元免运费</dd>")+'<dd><a ytag="04701" class="balance" href="http://buy.'+G.domain+'/cart.html" title="去购物车结算">去购物车结算</a></dd></dl></ul>',n=function(a){var b={total_count:0,total_price:0,rows:[]},c=4702;$.each(a,function(a,d){b.total_count+=parseInt(d.buy_count);b.total_price+=d.price*d.buy_count/100;b.rows.push({product_url:"http://item."+G.domain+"/item-"+d.product_id+".html",product_name:d.name,product_img:G.logic.constants.getPic60Url(d.product_char_id,0),product_price:(d.price/
100).toFixed(1),product_count:d.buy_count,ytag1:c++,ytag2:c++})});b.total_price=b.total_price.toFixed(1);return G.ui.template.fillWithTPL(!1,b,!1,h)};e||(a.html("加载中…"),b?$.getJSON("http://"+G.DOMAIN.BUY_ICSON_COM+"/json.php?mod=shoppingcart&act=list&callback=?&uid="+b,function(b){if(b&&b.hasOwnProperty("errno"))switch(e=!0,b.errno=parseInt(b.errno),b.errno){case 0:b=n(b.data);a.html(b);break;case 3:a.html("服务器出了点小状况，请稍候...")}}):G.util.localShare(function(b){b=b.getItem("shoppingcart");var c=[];b&&
$.each(b.list,function(a,b){c.push(b[0]+"|"+b[1]+"|"+b[2])});0<c.length&&G.util.post("http://"+G.DOMAIN.BUY_ICSON_COM+"/json.php?mod=shoppingcart&act=listnotlogin",{cart:c.join(",")},function(b){if(b&&b.hasOwnProperty("errno"))switch(e=!0,b.errno=parseInt(b.errno),b.errno){case 0:b=n(b.data);a.html(b);break;case 3:a.html("服务器出了点小状况，请稍候...")}},"jsonp")}))}else{var q=G.common.headConfig.CART,t="";q.img&&(t='<div class="cart_list_seven_year"><a target="_blank" href="'+q.url+'" title="'+q.name+'"><img src="'+
q.img+'" /></a></div>');a.css({width:196});$("#J_cartInfo_a").removeClass("cart_wrap_empty");b?a.html('<div style="padding:25px 10px;line-height:20px;"><p>您的购物车是空的</p><p>快挑选喜欢的商品加入购物车吧</p>'+t+"</div>"):a.html('<div style="padding:25px 10px;line-height:20px;"><p>您的购物车是空的</p><p>如您已添加商品，可<a style="color:#317EE7" href="https://base.'+G.domain+"/login.html?url="+encodeURIComponent(location.href)+'">登录</a>查看</p>'+t+"</div>")}};b?$.getJSON("http://d."+G.domain+"/json.php?mod=ajax&act=cart&callback=?",function(a){f(a&&
0==a.errno&&a.data.num||0)}):G.util.localShare(function(a){a=a.getItem("shoppingcart");var b=0;a&&$.each(a.list,function(a,c){b+=c[1]-0});f(b)})}},category:{config:{headIn:10,headOut:100,panelOut:200,liIn:100},ytag_base:85,FIRSTTPL:'<div id="i_sort_list">\t<div class="cate_normal">\t\t<@first_list@>\t\t<div cateid="{id}" class="item">\t\t\t<div class="item_hd">\t\t\t\t<dl>\t\t\t\t\t<dt class="top_cate">\t\t\t\t\t\t<a hotname="I.CATEGORY.FIRST.{index}" href="{url}" target="_blank" ytag="{ytag}">{text}<i class="dot_cate"></i></a>\t\t\t\t\t\t{hllink}\t\t\t\t\t</dt>\t\t\t\t\t<dd class="sub_cate">\t\t\t\t\t\t<@key_list@>\t\t\t\t\t\t<a hotname="I.CATEGORY.FIRST.KEYWORD.{index}" target="_blank" href="{url}" ytag="{ytag}">{name}</a>\t\t\t\t\t\t<@_key_list@>\t\t\t\t\t</dd>\t\t\t\t</dl>\t\t\t</div>\t\t\t<div class="item_bd">\t\t\t</div>\t\t</div>\t\t<@_first_list@>\t</div>\t<div class="cate_easy">\t\t<@easy_list@>\t\t<div cateid="{id}" class="item">\t\t\t<div class="item_hd">\t\t\t\t<dl>\t\t\t\t\t<dt class="top_cate">\t\t\t\t\t\t<a hotname="I.CATEGORY.FIRST.{index}" target="_blank" href="{url}" ytag="{ytag}">{text}<i class="dot_cate"></i></a>\t\t\t\t\t\t{hllink}\t\t\t\t\t</dt>\t\t\t\t</dl>\t\t\t</div>\t\t\t<div class="item_bd">\t\t\t</div>\t\t</div>\t\t<@_easy_list@>\t</div></div>',
SECONDTPL:'<div class="list">\t<@second_list@>\t<dl>\t\t<dt class="t">{second_name}</dt>\t\t<dd>\t\t\t<@third_list@>\t\t\t<a hotname="I.CATEGORY.SECOND.{index}" target="_blank" href="{url}" ytag="{ytag}">{name}</a>\t\t\t<@_third_list@>\t\t</dd>\t</dl>\t<@_second_list@></div><div class="hot">\t<@recommend_img_list@>\t{recommend_img_list_html}\t<@_recommend_img_list@>\t<@recommend_list@>\t\t<p class="t">{recommend_name}</p>\t<ul>\t\t<@recommend_link_list@>\t\t<li><a hotname="I.CATEGORY.RECOMMEND.{index}" href="{recommend_link_url}" target="_blank" ytag="{ytag}">{recommend_link_name}</a></li>\t\t<@_recommend_link_list@>\t</ul>\t<@_recommend_list@></div>{iframe_str}',
renderFirst:function(){var a=this,b=$("#category_panel");if(0!=b.length){var c={first_list:[],easy_list:[]},d=1,e=G.logic.constants.getSiteId(),f=['<a hotname="I.CATEGORY.FIRST.KEYWORD.10.9" target="_blank" href="http://act.'+G.domain+'/recommend.html" class="link_extra" ytag="87009">装机宝<i>&nbsp;</i></a>','<a hotname="I.CATEGORY.FIRST.KEYWORD.10.1" target="_blank" href="http://act.'+G.domain+'/carproduct.html" class="link_extra" ytag="94001">爱车宝<i>&nbsp;</i></a>','<span style="color:#333333">，</span><a hotname="I.CATEGORY.FIRST.KEYWORD.10.15" target="_blank" href="http://chong.'+
G.domain+'" ytag="98001">充值中心<i>&nbsp;</i></a>','<a hotname="I.CATEGORY.FIRST.KEYWORD.1.10" target="_blank" href="http://event.'+G.domain+'/event/80316703.html" class="link_extra" ytag="85009">合约机<i>&nbsp;</i></a>','<a hotname="I.CATEGORY.FIRST.KEYWORD.1.10" target="_blank" href="http://event.'+G.domain+'/event/80868722.html" class="link_extra" ytag="85009">合约机<i>&nbsp;</i></a>','<span style="color:#333333">，</span><a hotname="I.CATEGORY.FIRST.KEYWORD.10.11" target="_blank" href="http://www.'+G.domain+
'/household_clean.html" ytag="95001">家庭清洁<i>&nbsp;</i></a>','<span style="color:#333333">，</span><a hotname="I.CATEGORY.FIRST.KEYWORD.10.12" target="_blank" href="http://www.'+G.domain+'/daily_food.html" ytag="96000">食品<i>&nbsp;</i></a><span style="color:#333333">，</span><a hotname="I.CATEGORY.FIRST.KEYWORD.10.12" target="_blank" href="http://www.'+G.domain+'/home_furnishing.html" ytag="96000">家居百货<i>&nbsp;</i></a>'];$.each(window.CATEGORY_CONFIG,function(b,g){var k="";"硬件/外设"==g.text&&(k=f[0]);"汽车用品"==
g.text&&(k=f[1]);if("票务旅游"==g.text||"机票酒店"==g.text)k=f[2];"手机/配件"==g.text&&1001==e&&(k=f[3]);"手机/配件"==g.text&&1==e&&(k=f[4]);"个人护理"==g.text&&(k=f[5]);"母婴"==g.text&&(k=f[6]);var l={id:b,ytag:1E3*(a.ytag_base+d-1),index:d,url:g.url+("#"===g.url?'" onclick="return false':'" style="cursor:pointer'),text:g.text,key_list:[],hllink:k,citem:1==d||2==d||5==d?'class="item"':""},m=l.index,n=1;d++;g.keyword=g.keyword||[];$.each(g.keyword,function(b,c){l.key_list.push({name:c.text,url:c.url,ytag:10<n?"":1E3*(a.ytag_base+
m-1)+n,index:m+"."+n});n++});g.highlight?c.first_list.push(l):c.easy_list.push(l)});b.html(G.ui.template.fillWithTPL(!1,c,!1,a.FIRSTTPL));$("#i_sort_list .cate_easy>div:first-child").addClass("item_first");b.mouseleave(function(){a.clearTimeout();a.panelOutTimer=setTimeout(function(){$("#i_sort_list>div>div").removeClass("item_hover");$("#i_sort_list>div>div .i_cont_iframe").css({display:"none"});a.needSlide&&$("#category_container").removeClass("i_status_on")},a.config.panelOut)})}},clearTimeout:function(){this.headInTimer&&
clearTimeout(this.headInTimer);this.headOutTimer&&clearTimeout(this.headOutTimer);this.panelOutTimer&&clearTimeout(this.panelOutTimer);this.liInTimer&&clearTimeout(this.liInTimer);this.liInTimer=this.panelOutTimer=this.headOutTimer=this.headInTimer=0},renderSecond:function(a){var b=$.browser.msie&&6==$.browser.version,c=this,d=parseInt($(a).attr("cateid")),e={second_list:[],recommend_list:[],iframe_str:b?'<iframe class="i_cont_iframe" style="width:0px;height:0px"></iframe>':"",recommend_img_list:[]},
f=1;$.each(window.CATEGORY_CONFIG[a.attr("cateid")].list,function(a,b){var k={second_name:b.text,third_list:[]},l=1;$.each(b.list,function(a,b){k.third_list.push({name:b.text,url:b.url,ytag:50<l?"":1E3*(c.ytag_base+d)+100+50*(f-1)+l,index:d+"."+f+"."+l});l++});e.second_list.push(k);f++});f=1;$.each(window.CATEGORY_CONFIG[a.attr("cateid")].recommend||{},function(b,g){var k={recommend_name:g.name,recommend_link_list:[]},l=1;$.each(g.list,function(a,b){k.recommend_link_list.push({recommend_link_name:b.text,
recommend_link_url:b.url,ytag:1E3*(c.ytag_base+d)+(1E3-l),index:d+"."+f+"."+l});l++});e.recommend_list.push(k);e.recommend_img_list.push({recommend_img_list_html:'<a id="hot_img'+a.attr("cateid")+'" class="hot_img" title="" hotname="I.CATEGORY.HOTIMG.'+d+"."+f+'.1" ytag="'+parseInt(1E3*(c.ytag_base+d)+(1E3-(l+10)))+'"><script type="text/javascript">G.logic.header.category.showAdv('+a.attr("cateid")+");\x3c/script></a>"});f++});a.find(".item_bd").html(G.ui.template.fillWithTPL(!1,e,!1,this.SECONDTPL));
this.adjustPanelPos(a)},showAdv:function(a){var b=G.logic.constants.getSiteId();G.logic.constants.categoryAds[a]&&(G.logic.getAdItem(b,"mobile-shouyefenleidaohang",G.logic.header.category.setCategoryAd),G.logic.header.category.curCategory=$("#hot_img"+a),G.logic.header.category.curCateId=a)},curCategory:"",curCateId:"",setCategoryAd:function(a){var b=[],c=a[G.logic.constants.categoryAds[G.logic.header.category.curCateId][0]];a=a[G.logic.constants.categoryAds[G.logic.header.category.curCateId][1]];
var d,e;G.logic.header.category.curCategory&&(d=G.logic.header.category.curCategory.attr("hotname"),e=G.logic.header.category.curCategory.attr("ytag"));if(c){var f,h;for(h in c)f=c[h],""!=f.img_wide&&b.push('<a href="'+f.url+'" hotname="'+d+'" ytag="'+e+'" target="_blank"><img src="'+f.img_wide+'" alt="'+f.content+'" title="'+f.content+'"></a>')}if(a)for(var g in a)c=a[g],""!=c.img_wide&&b.push('<a href="'+c.url+'" hotname="'+d+'" ytag="'+e+'" target="_blank"><img src="'+c.img_wide+'" alt="'+c.content+
'" title="'+c.content+'"></a>');""!=G.logic.header.category.curCategory&&G.logic.header.category.curCategory.html(b.join(""));return!1},adjustPanelPos:function(a){var b=$.browser.msie&&6==$.browser.version,c=a.find(".item_bd");b&&c.find(".i_cont_iframe").css({width:c.width(),height:c.height()});b=parseFloat(a.offset().top,10);a=parseFloat(a.outerHeight(),10);var d=parseFloat(c.outerHeight(),10),e=parseFloat($("#category_panel").offset().top,10),f=parseFloat($(window).scrollTop(),10),h=parseFloat($(window).height(),
10)-d-b-20+f;h<e-b-2&&(h=e-b-2);h<f-b-1&&(h=f-b-1);-2<h&&(h=-2);h<a-d+1&&(h=a-d+1);c.css({top:h+"px"})},mousehover:function(a){$("#i_sort_list>div>div").removeClass("item_hover");$("#i_sort_list>div>div .i_cont_iframe").css({display:"none"});a.addClass("item_hover");a.find(".i_cont_iframe").css({display:""});a.data("rendered")?this.adjustPanelPos(a):(a.data("rendered",!0),this.renderSecond(a))},showPanel:function(){var a=this;a.sendRequest(function(){a.renderFirst();$("#i_sort_list>div>div").mouseenter(function(){var b=
$(this);a.clearTimeout();a.liInTimer=setTimeout(function(){!1===b.hasClass("item_hover")&&a.mousehover(b)},a.config.liIn)})})},sendRequest:function(a){var b=this;b.callbackList=b.callbackList||[];void 0===window.CATEGORY_CONFIG?(b.callbackList.push(a),G.logic.constants.getWhId(function(a){var d=["","11","1011"],e=G.util.cookie.get("areasInfo").split("_"),e=parseInt(e[0].replace(/\D/,""))?parseInt(e[0].replace(/\D/,"")):0;a=d[e]?d[e]:a;d=parseInt(new Date/3E5);e="http://st.icson.com/static_v1/js/app/categories_"+
a+".js?v="+d;G.prefix.ssl&&(e="http://st.icson.com/static_v1/js/app/categories_"+a+".js?v="+d);$.ajax({type:"get",dataType:"script",url:e,crossDomain:!0,cache:!0,scriptCharset:"gbk",success:function(){for(;b.callbackList.length;)b.callbackList.shift().call(b)},context:b})})):a.call(b)},init:function(){var a=this,b=$("#category_container");if(0!==b.length){var c=a.needSlide=!b.hasClass("i_status_on");c&&b.find(">h3:first-child").hover(function(){a.clearTimeout();a.headInTimer=setTimeout(function(){b.addClass("i_status_on");
$("#i_sort_list>div>div").removeClass("item_hover");$("#i_sort_list>div>div .i_cont_iframe").css({display:"none"});a.showPanel()},a.config.headIn)},function(){a.clearTimeout();a.headOutTimer=setTimeout(function(){b.removeClass("i_status_on")},a.config.headOut)});!c&&a.showPanel()}}},openKF:function(){var a=($(window).width()-504)/2,b=($(window).height()-404)/2;G.logic.constants.getWhId(function(c){window.open(G.logic.header._kefuLink[c],"_blank","height=404,width=504,toolbar=no,scrollbars=no,menubar=no,status=no,left="+
a+",top="+b)})},initTopAdvertise:function(a,b){var c=this,d=arguments;if(void 0===a)G.logic.constants.getWhId(function(a){$.ajax({type:"GET",url:"http://"+G.DOMAIN.ACT_ICSON_COM+"/json.php?mod=topadv&act=page&jsontype=str",success:function(a){d.callee.call(c,a,b)},dataType:"jsonp",cache:!0,crossDomain:!0,jsonpCallback:"loadtopadv_"+a})});else if(a&&!($.isEmptyObject(a)||!a.ssbg&&!a.bsbg)){var e={},f=1280<=window.screen.availWidth&&!1!==b;$.each(["s","b"],function(b,c){e[c]=a[c+"sbg"]?G.ui.template.fillWithTPL(!1,
{target:a[c+"tar"],background:a[c+(f?"b":"s")+"bg"],href:a[c+"href"]},!1,'<a target="{target}" style="background:url({background})" href="{href}"></a>'):""});if(!e.s||!e.b){var h=$('<div class="top_banner">'+(e.s||e.b)+"</div>");$(".i_wrap_tooolbar").prepend(h);h.css("height",e.b?"200px":"40px")}else{var g=function(a){var b=$('<div class="top_banner">'+e.s+"</div>");$(".i_wrap_tooolbar").prepend(b);var c=function(){b.html(e.b);b.animate({height:"200px"},400,function(){})},d=function(){b.animate({height:"40px"},
200,function(){b.html(e.s)})},f={1:"sh",1001:"sz",2001:"bj"};f[a]&&!G.util.cookie.get("indextopadv_"+f[a])?(c(),setTimeout(function(){d()},3E3),G.util.cookie.add("indextopadv_"+f[a],"1","/",864E3,""+G.domain)):b.html(e.s).css("height","40px")};G.logic.constants.getWhId(function(a){g(a)})}}},initTopNotice:function(){$(function(){if("page"in G&&"notice"in G.page&&"array"==$.type(G.page.notice)&&0<G.page.notice.length){var a=[],b=[],c=6501;$.each(G.page.notice,function(a,e){b.push('<li _notice_id="'+
e.id+'"><a ytag="0'+c++ +'" href="'+(e.link||"javascript:;")+'" target="_blank">'+e.content+"</a></li>")});0<b.length&&(a.push('<div id="PageTopNotice" class="yx_wrap yx_wrap_notice">\t<div class="yx_notice">\t\t<div class="mod_mask"></div>\t\t<div class="mod_notice">\t\t\t<i class="dot_speak"></i>\t\t\t<div class="notice_list">\t\t\t\t<ul>'),a.push(b.join("")),a.push("</ul>\t\t\t</div>\t\t</div>\t</div></div>"),$(a.join("")).insertAfter($("div.yx_top_toolbar")),1<b.length&&(G.logic.header.asHander=
setInterval('G.logic.header.autoScroll(".notice_list")',3E3)))}})},initDefaultSearch:function(){if(!1!==(void 0!==window.G&&void 0!==window.G.page&&void 0!=window.G.page.defaultSearch&&!$.isEmptyObject(G.page.defaultSearch))){var a=$.trim(G.page.defaultSearch.title),b=$.trim(G.page.defaultSearch.href);if(a&&b){var c=$("#q_show"),d=c.data("events");if(d&&d.focus){c.data("events").focus[0].data.opt.defaultValue=a;G.logic.header._Q_SHOW_DEF_TEXT=a;c.val(a).attr("_href",b);var e=$("#yx_slogan");if(e.length){if($("#yx_slogan").attr("ini"))return;
$("#yx_slogan").attr("ini",1);var f="+=130",h=0,g=function(){if(2==h||0==h)f="+=130"==f?"-=130":"+=130";e.animate({left:f},1500,function(){"+=130"==f?h--:h++;setTimeout(g,3E3)})};setTimeout(g,3E3)}$("#top_service_num").length&&!$("#top_service_num").attr("ini")&&($("#top_service_num").attr("ini",1),G.app.header={},G.app.header.msgNum=0,G.app.header.isInit=!1,G.app.header.handleMsg=function(a){if(a&&0==a.errno&&a.data){if(isNaN(parseInt(a.data))){if(a.data.length){for(var b=0,c=0;c<a.data.length;c++){var d=
a.data[c],b=d.count+b;d.count&&$("#top_service_content").append("<li>"+d.count+"条"+d.name+'回复，<a target="_blank" href="'+d.url+'">查看</a></li>')}G.app.header.msgNum+=b;G.app.header.msgNum&&$("#top_service_num").html(G.app.header.msgNum)}}else G.app.header.msgNum+=parseInt(a.data),$("#top_service_content").append("<li>"+a.data+'条价格保护赔付，<a target="_blank" href="'+a.url+'">查看</a></li>');if(!G.app.header.isInit&&G.app.header.msgNum){G.app.header.isInit=!0;var e;$("#top_service_trigger").mouseenter(function(){$("#top_service_layer").show();
clearTimeout(e);e=setTimeout(function(){$("#top_service_layer").hide()},3E3)});$("#top_service_layer").mouseenter(function(){e&&clearTimeout(e)});$("#top_service_layer").mouseleave(function(){$("#top_service_layer").hide()})}G.app.header.msgNum&&($("#top_service_num").html(G.app.header.msgNum),$("#top_service_num").show())}},G.logic.login.getLoginUser(function(a){a&&(a.data&&$("#top_service_num").length)&&($.ajax({url:"http://d."+G.domain+"/json.php?mod=ajax&act=getPriceRecord&callback=G.app.header.handleMsg",
dataType:"script",cache:!1,scriptCharset:"gb2312"}),$.ajax({url:"http://service."+G.domain+"/json.php?mod=orderurge&act=getnoticemsg&callback=G.app.header.handleMsg",dataType:"script",cache:!1,scriptCharset:"gb2312"}))}))}}}},closeTopNotice:function(){var a=$("#PageTopNotice");0<a.length&&G.util.localShare(function(b){var c=b.getItem("index.top_notice")||[];if("object"==$.type(c)){var d=[];$.each(c,function(a,b){d[a]=b});c=d}a.find("li").each(function(a,b){var d=$(b),d=parseInt(d.attr("_notice_id"));
NaN!=d&&0<d&&(10==c.length&&c.pop(),-1==$.inArray(d,c)&&c.push(d))});b.setItem("index.top_notice",c);a.animate({height:0},200,function(){$(this).hide();""!=G.logic.header.asHander&&clearInterval(G.logic.header.asHander)})})},autoScroll:function(a){$(a).find("ul:first").animate({marginTop:"-24px"},500,function(){$(this).css({marginTop:"0px"}).find("li:first").appendTo(this)})},asHander:"",checkProvId:function(){if(1!=G.util.cookie.get("prid_check")){var a="";$.get("http://"+G.DOMAIN.BASE_ICSON_COM+
"/json.php?mod=user&act=getrealprid",function(b){b&&0==b.errno&&(a=b.prid);if(G.logic.constants.serviceAreas[a]&&G.logic.constants.serviceAreas[a][1]!=G.logic.constants.getSiteId()){var c=[],d=1200,e=G.logic.constants.getProvId();b=G.logic.constants.serviceAreas[e][0];var f=G.logic.constants.serviceAreas[a][0];$.each(G.logic.constants.allowedWhInfo,function(a,b){for(var f='<div class="storage_item"><p>'+b+"仓服务：</p><ul>",l=0;31>l;l++){var m=G.logic.constants.serviceAreasSeq[l],n=G.logic.constants.serviceAreas[m];
if(a==n[1]){var q=e==m?"":'alt="前往'+n[0]+'" title="前往'+n[0]+'"';d++;f+='<li><a ytag="0'+d+'"'+q+' href="#"  onclick="G.logic.header.changeProv(this);return false;" w="'+a+'" p="'+m+'">'+n[0]+"</a></li>"}}c.push(f+"</ul></div>")});b='<div class="yx_pop_areatip">\t\t\t\t        <div class="areatip_hd">\t\t\t\t          <dl>\t\t\t\t            <dt>请选择本次购物送至省份，以获得准确的商品信息。</dt>\t\t\t\t            <dd>送至当前IP所在省份：<a ytag="01401" href="#" onclick="G.logic.header.changeProv(this);return false;" class="btn_strong" w="'+
G.logic.constants.serviceAreas[a][1]+'" p="'+a+'">'+f+'</a>　上次收货省份：<a ytag="01402" href="#" onclick="G.logic.header.changeProv(this);return false;" class="btn_strong" w="'+G.logic.constants.serviceAreas[e][1]+'" p="'+e+'">'+b+"</a></dd>\t\t\t\t          </dl>\t\t\t\t          <p class=\"other_select\"><a href=\"javascript:;\" hidefocus=\"true\" onclick=\"if ($('.areatip_bd').css('display') == 'none') {$('.areatip_bd').slideDown('fast');$(this).parent().addClass('other_select_open');G.logic.header.dialog.resizeNoCenter({height: '386'});} else {$('.areatip_bd').slideUp('fast');$(this).parent().removeClass('other_select_open');G.logic.header.dialog.resizeNoCenter({height: '170'});};\">选择其他省份<i class=\"arrow\"></i></a></p>\t\t\t\t        </div>\t\t\t\t        <div class=\"areatip_bd\">"+
c.join("")+'<p class="tip">易迅商品暂时只支持配送至中国大陆地区</p>\t\t\t\t\t\t        </div>\t\t\t\t\t\t      </div>\t\t\t\t\t\t    </div>\t\t\t\t\t\t  </div>';G.ui.popup._msgPopup=G.ui.popup.create({title:"欢迎来到易迅网",width:500,height:170,fullscreen:1});G.logic.header.dialog=G.ui.popup.showMsg("",1,function(){},function(){G.logic.header.closeCheckProvId()},function(){},"","");$(".layer_global_cont").html(b);$(".layer_global_cont").removeClass("layer_cont_15")}},"jsonp")}},dialog:"",closeCheckProvId:function(){$("#positionFixedID0").hide();
G.util.cookie.add("prid_check",1,"/",604800,"."+G.domain)},setProvId:function(a){G.logic.header.switchSite(G.logic.constants.serviceAreas[a][0],a);G.logic.constants.setLocationId(G.logic.constants.serviceAreas[a][2]+"_"+a)},changeProv:function(a){G.logic.constants.serviceAreas[$(a).attr("p")]&&($(a).attr("p")!=G.logic.constants.getProvId()?(G.logic.header.switchSite($(a).attr("w"),$(a).attr("p")),G.logic.constants.setLocationId(G.logic.constants.serviceAreas[$(a).attr("p")][2]+"_"+$(a).attr("p"))):
G.logic.header.dialog.close(),G.logic.header.closeCheckProvId())}};
logStat={getLog:function(a){a=a.target;var b,c;a.getAttribute("lg")?b=a:a.parentNode&&("A"==a.parentNode.tagName&&a.parentNode.getAttribute("lg"))&&(b=a.parentNode);b&&(c=b.getAttribute("lg"),c+=b.getAttribute("pos")?"{|}"+b.getAttribute("pos"):"{|}1",b.getAttribute("href")&&-1==b.getAttribute("href").indexOf("#")?c=c+"{|}"+escape(b.getAttribute("href")):b.getAttribute("title")?c=c+"{|}"+b.getAttribute("title"):b.getAttribute("alt")?c=c+"{|}"+b.getAttribute("alt"):"INPUT"==b.tagName||"BUTTON"==b.tagName||
""==b.innerText?(a=(a=b.id?b.id:b.name)?a:b.tagName,c=c+"{|}"+a):c=c+"{|}"+b.innerText,c=b.getAttribute("lgType")?b.getAttribute("lgType")+"{|}"+c:"_blank"===b.getAttribute("target")?"0{|}"+c:"1{|}"+c,G.logic.constants.getWhId(function(a){var b={1:4,1001:10,2001:13,3001:42,4001:43,5001:44};a=b[a]?b[a]:4;logStat.chkLog(a+"{|}"+c)}))},chkLog:function(a){var b="http://search.paipai.com/cgi-bin/clicklog",c,d=G.util.cookie.get("visitkey"),e=G.util.cookie.get("uid"),f=escape(document.URL);c=a.split("{|}");
3E3==c[2]?G.logic.constants.getWhId(function(a){var e={1:4,1001:10,2001:13,3001:42,4001:43,5001:44};a=e[a]?e[a]:4;b=b+"?srcid="+a+"&uin="+c[5]+"&ls="+c[2]+"&subls="+c[3]+"&visitKey="+d+"&ref="+f+"&herf="+c[4];logStat.loadScript(b+"&t="+(new Date).getTime(),"chkStatScript")}):c[2]&&(b=b+"?srcid="+c[0]+"&uin="+e+"&ls="+c[2]+"&subls="+c[3]+"&visitKey="+d+"&ref="+f+"&herf="+c[4],"1"==c[1]?G.util.cookie.add("lgStat",b,"/",0,"."+G.domain):logStat.loadScript(b+"&t="+(new Date).getTime(),"chkStatScript"))},
chkItem:function(a,b,c,d){G.logic.constants.getWhId(function(e){e="http://search.paipai.com/cgi-bin/search_log?srcid="+{1:4,1001:10,2001:13,3001:42,4001:43,5001:44}[e]+"&";var f=G.util.cookie.get("visitkey"),h=$("#q_show"),g="";0<h.length&&(g=h.val(),g="输入品牌或商品进行搜索"===g?"":g);h=G.util.cookie.get("uid");e=e+"pos="+a+"&visitkey="+f+"&uin="+h+"&ref="+escape(document.URL)+"&commid="+b+"&leafclassid="+(c||"")+"&keyword="+g+"&t="+(new Date).getTime();void 0===d?G.util.cookie.add("lgStat",e,"/",0,"."+G.domain):
logStat.loadScript(e)})},initStat:function(a){if(a)for(var b in a)this[b]=a[b];$(document).bind("click",logStat.getLog);var c=G.util.cookie.get("lgStat");c&&setTimeout(function(){logStat.loadScript(c+"?t="+(new Date).getTime());G.util.cookie.del("lgStat","."+G.domain)},0)},loadScript:function(a,b,c){setTimeout(function(){var d=document.createElement("script"),e=(new Date).getTime(),f=(c||{}).charset||"gb2312";b=b?b+e:e;d.charset=f;d.id=b;document.getElementsByTagName("head")[0].appendChild(d);d.src=
a;return d},0)}};$.browser.msie||HTMLElement.prototype.__defineGetter__("innerText",function(){for(var a="",b=this.childNodes,c=0;c<b.length;c++)1==b[c].nodeType?a+=b[c].innerText:3==b[c].nodeType&&(a+=b[c].nodeValue);return a});
G.logic.getAdItem=function(a,b,c,d){G.logic.getAdItem.options=G.logic.getAdItem.options||{beforeFunc:{},afterFunc:{}};a=a+"_"+b;c&&$.isFunction(c)&&(G.logic.getAdItem.options.beforeFunc[a]=c);d&&$.isFunction(d)&&(G.logic.getAdItem.options.afterFunc[a]=d);$.ajax({url:"http://d.icson.com/ad/"+a+".js",dataType:"script",cache:!1,scriptCharset:"gb2312"})};
G.logic.getAdItem.dealAd=function(a,b,c){b=b+"_"+c;if(!(G.logic.getAdItem.options.beforeFunc[b]&&!1===G.logic.getAdItem.options.beforeFunc[b](a))){var d=1280<=window.screen.availWidth?1:0;$("div[ad_id]").each(function(){var b=$(this),c=b.attr("ad_id");if(a[c]){var h="";b.html().replace(/\x3c!--\s*((?:.|\s)+?)\s*--\x3e/,function(a,b){h=b});var g="",k=0,l;for(l in a[c])var m=a[c][l],n={url:m.url,img:d||!m.img_narrow?m.img_wide:m.img_narrow,width:d||!m.img_narrow?m.w_width:m.n_width,height:d||!m.img_narrow?
m.w_height:m.n_height,text:m.content,index:++k},g=g+h.replace(/{(url|img|text|index|width|height)}/g,function(a,b){return n[b]});b.replaceWith(g)}});if(G.logic.getAdItem.options.afterFunc[b])G.logic.getAdItem.options.afterFunc[b](a)}};
G.logic.productpool={load:function(a,b,c,d){$.ajax({url:"http://d.icson.com/productpool/"+a+"_"+b+".js?v="+(new Date).getTime(),dataType:"script",success:function(){$.isFunction(c)&&!1===c(G.logic.productpool.data)||(G.logic.productpool._parse(),$.isFunction(d)&&d(G.logic.productpool.data))},error:function(){G.logic.productpool.data={};G.logic.productpool._parse()}})},_parse:function(){$("div[pp_id]").each(function(){var a=$(this),b=a.attr("pp_id");if(G.logic.productpool.data[b]){var c="";a.html().replace(/\x3c!--\s*((?:.|\s)+?)\s*--\x3e/,
function(a,b){c=b});var d="",e=0,f;for(f in G.logic.productpool.data[b].products){for(var h=G.logic.productpool.data[b].products[f],g=h.selling_point.split(";");4>g.length;)g.push("");var k={index:++e,name:h.name,desc:h.description,img:h.pic_url,url:h.link,text:h.text,price:h.icson_price,cur_price:h.promotional_price||"",sell_point1:g[0],sell_point2:g[1],sell_point3:g[2],sell_point4:g[3]},h="",l;for(l in k)h=""==h?l:h+("|"+l);d+=c.replace(RegExp("{("+h+")}","g"),function(a,b){return k[b]})}a.replaceWith(d)}})}};
/*  |xGv00|b1ac8b33a1dad4cceb85d4a7ab4af818 */